export enum QueryTag {
  CurrentUser = 'CurrentUser',
  Workspace = 'Workspace',
  Account = 'Account',
  AccountUser = 'AccountUser',
  WorkspaceAsset = 'WorkspaceAsset',
  AccountUserPermission = 'AccountUserPermission',
  AccountWorkspace = 'AccountWorkspace',
  AccountResource = 'AccountResource',
  AccountWorkspaceSpecification = 'AccountWorkspaceSpecification',
  AccountWorkspaceSpecificationMCPToken = 'AccountWorkspaceSpecificationMCPToken',
  AccountWorkspaceIntegration = 'AccountWorkspaceIntegration',
  AccountWorkspaceIntegrationJiraProject = 'AccountWorkspaceIntegrationJiraProject',
  AccountWorkspaceIntegrationJiraConfluenceSpace = 'AccountWorkspaceIntegrationJiraConfluenceSpace',
  AccountWorkspaceIntegrationProvider = 'AccountWorkspaceIntegrationProvider',
  AccountWorkspaceAssetFile = 'AccountWorkspaceAssetFile',
  AccountWorkspaceIntegrationRepo = 'AccountWorkspaceIntegrationRepo',
  AccountWorkspaceSpecificationVersion = 'AccountWorkspaceSpecificationVersion',
  CodeReport = 'CodeReport',
  CodeReportSection = 'CodeReportSection',
  AccountWorkspaceSpecificationVersionDomain = 'AccountWorkspaceSpecificationVersionDomain',
  AccountWorkspaceSpecificationVersionDiagram = 'AccountWorkspaceSpecificationVersionDiagram',
  AccountWorkspaceAssetQualityIssue = 'AccountWorkspaceAssetQualityIssue',
  Preset = 'Preset',
}
