/* tslint:disable */
/* This is generated by ts_routes-rails */

export type ScalarType = string | number | boolean;

function $buildOptions(options: any, names: string[]): string {
  if (options) {
    let anchor = "";
    const q = [] as string[];
    for (const key of Object.keys(options)) {
      if (names.indexOf(key) !== -1) {
        // the key is already consumed
        continue;
      }

      const value = options[key];

      if (key === "anchor") {
        anchor = `#${$encode(value)}`;
      } else {
        $buildQuery(q, key, value);
      }
    }
    return (q.length > 0 ? "?" + q.join("&") : "") + anchor;
  } else {
    return "";
  }
}

function $buildQuery(q: string[], key: string, value: any) {
  if ($isScalarType(value)) {
    q.push(`${$encode(key)}=${$encode(value)}`);
  } else if (Array.isArray(value)) {
    for (const v of value) {
      $buildQuery(q, `${key}[]`, v);
    }
  } else if (value != null) {
    // i.e. non-null, non-scalar, non-array type
    for (const k of Object.keys(value)) {
      $buildQuery(q, `${key}[${k}]`, value[k]);
    }
  }
}

function $encode(value: any): string {
  return encodeURIComponent(value);
}

function $isScalarType(value: any): value is ScalarType {
  return (
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  );
}

function $isPresent(value: any): boolean {
  return value != null && ("" + value).length > 0;
}

function $hasPresentOwnProperty(options: any, key: string): boolean {
  return options && options.hasOwnProperty(key) && $isPresent(options[key]);
}

/** /api/v1/auth/:provider(.:format) */
export function apiV1AuthPath(provider: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "auth" + "/" + provider + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["provider","format"]);
}

/** /api/v1/auth/:provider/callback(.:format) */
export function apiV1AuthCallbackPath(provider: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "auth" + "/" + provider + "/" + "callback" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["provider","format"]);
}

/** /api/v1/auth/failure(.:format) */
export function apiV1AuthFailurePath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "auth" + "/" + "failure" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/sessions(.:format) */
export function apiV1SessionsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/current_user(.:format) */
export function apiV1CurrentUserPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "current_user" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/terminal_sessions/:id/finish_auth(.:format) */
export function finishAuthApiV1TerminalSessionPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "terminal_sessions" + "/" + id + "/" + "finish_auth" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/terminal_sessions/:id/cancel(.:format) */
export function cancelApiV1TerminalSessionPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "terminal_sessions" + "/" + id + "/" + "cancel" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/terminal_sessions(.:format) */
export function apiV1TerminalSessionsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "terminal_sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/terminal_sessions/:id(.:format) */
export function apiV1TerminalSessionPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "terminal_sessions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/internal/ws_auth(.:format) */
export function apiV1InternalWsAuthPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "internal" + "/" + "ws_auth" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/users(.:format) */
export function apiV1CompanyUsersPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "users" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/users/:id(.:format) */
export function apiV1CompanyUserPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "users" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/config_items(.:format) */
export function apiV1CompanyConfigItemsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "config_items" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/config_items/:id(.:format) */
export function apiV1CompanyConfigItemPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "config_items" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/projects/:project_id/collaborators(.:format) */
export function apiV1CompanyProjectCollaboratorsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "collaborators" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/collaborators/:id(.:format) */
export function apiV1CompanyProjectCollaboratorPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "collaborators" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/config_items(.:format) */
export function apiV1CompanyProjectConfigItemsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "config_items" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/config_items/:id(.:format) */
export function apiV1CompanyProjectConfigItemPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "config_items" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects(.:format) */
export function apiV1CompanyProjectsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/projects/:id(.:format) */
export function apiV1CompanyProjectPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin(.:format) */
export function adminRootPath(options?: object): string {
  return "/" + "admin" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/users/:id/impersonate(.:format) */
export function impersonateAdminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + "/" + "impersonate" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/users/:id/stop_impersonate(.:format) */
export function stopImpersonateAdminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + "/" + "stop_impersonate" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/users(.:format) */
export function adminUsersPath(options?: object): string {
  return "/" + "admin" + "/" + "users" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/users/new(.:format) */
export function newAdminUserPath(options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/users/:id/edit(.:format) */
export function editAdminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/users/:id(.:format) */
export function adminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/companies(.:format) */
export function adminCompaniesPath(options?: object): string {
  return "/" + "admin" + "/" + "companies" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/companies/new(.:format) */
export function newAdminCompanyPath(options?: object): string {
  return "/" + "admin" + "/" + "companies" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/companies/:id/edit(.:format) */
export function editAdminCompanyPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "companies" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/companies/:id(.:format) */
export function adminCompanyPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "companies" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/projects(.:format) */
export function adminProjectsPath(options?: object): string {
  return "/" + "admin" + "/" + "projects" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/projects/new(.:format) */
export function newAdminProjectPath(options?: object): string {
  return "/" + "admin" + "/" + "projects" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/projects/:id/edit(.:format) */
export function editAdminProjectPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "projects" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/projects/:id(.:format) */
export function adminProjectPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "projects" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/project_collaborators(.:format) */
export function adminProjectCollaboratorsPath(options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/project_collaborators/new(.:format) */
export function newAdminProjectCollaboratorPath(options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/project_collaborators/:id/edit(.:format) */
export function editAdminProjectCollaboratorPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/project_collaborators/:id(.:format) */
export function adminProjectCollaboratorPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/agent_credentials(.:format) */
export function adminAgentCredentialsPath(options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/agent_credentials/new(.:format) */
export function newAdminAgentCredentialPath(options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/agent_credentials/:id/edit(.:format) */
export function editAdminAgentCredentialPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/agent_credentials/:id(.:format) */
export function adminAgentCredentialPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** / */
export function rootPath(options?: object): string {
  return "/" + $buildOptions(options, []);
}

/** /docs */
export function oasRailsPath(options?: object): string {
  return "/" + "docs" + $buildOptions(options, []);
}

/** /letter_opener */
export function letterOpenerWebPath(options?: object): string {
  return "/" + "letter_opener" + $buildOptions(options, []);
}

/** /letter_opener/ */
export function letterOpenerWebLettersPath(options?: object): string {
  return "/" + "letter_opener" + "/" + $buildOptions(options, []);
}

/** /letter_opener/clear(.:format) */
export function letterOpenerWebClearLettersPath(options?: object): string {
  return "/" + "letter_opener" + "/" + "clear" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /letter_opener/:id(/:style)(.:format) */
export function letterOpenerWebLetterPath(id: ScalarType, options?: object): string {
  return "/" + "letter_opener" + "/" + id + ($hasPresentOwnProperty(options, "style") ? "/" + (options as any).style : "") + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","style","format"]);
}

/** /letter_opener/:id/delete(.:format) */
export function letterOpenerWebDeleteLetterPath(id: ScalarType, options?: object): string {
  return "/" + "letter_opener" + "/" + id + "/" + "delete" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}
