# frozen_string_literal: true

FactoryBot.define do
  factory :company do
    name
    email_domain
    auto_accept_users { false }
    # slug is auto-generated by model callback

    trait :auto_accept do
      auto_accept_users { true }
    end

    trait :with_logo do
      after(:build) do |company|
        # TODO: Attach Shrine logo fixture when needed
        # company.logo = File.open(Rails.root.join('test', 'fixtures', 'files', 'logo.png'))
      end
    end
  end
end
