services:
  web:
    image: ${WEB_IMAGE}
    depends_on:
      - db
      - redis
    environment:
      APP_VERSION: dev
      AUTHOR_NAME: author
      AUTHOR_EMAIL: email
      RAILS_LOG_TO_STDOUT: 'true'
      PORT: 4000
      DB_HOST: db
      DEBUG: 'true'
      REDIS_URL: redis://redis:6379/1
      ENVIRONMENT: test
      RAILS_ENV: test

  db:
    image: quay.io/debezium/postgres:15-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: ghcr.io/redisgrafana/redis-opencv:latest
