import { existsSync } from 'node:fs';

import reactSwc from '@vitejs/plugin-react-swc';
import { defineConfig } from 'vitest/config';
import tsconfigPaths from 'vite-tsconfig-paths';

// Dedicated config — intentionally does NOT load ViteRuby()/inertia() from vite.config.ts,
// which assume a live Rails/Inertia context and break under Vitest (vitest#436).
// Keeps tsconfig path aliases (shared/ui, layouts/*, @/types/generated, test/*) and JSX.

// CI runners (2–4 vCPU) run these jsdom + userEvent tests ~6–10× slower than bare metal —
// with coverage on, the heaviest form-interaction tests (~0.8s locally) brush the default 5s
// ceiling and flake. Give slow runners generous headroom. This app's tests ALWAYS run inside the
// web container (the host has no node_modules that works — the bind-mounted native bindings are
// Linux), and Docker-on-Mac is CPU-throttled just like CI — so "in a container" is itself a
// slow-runner signal, not just CI. Without this, a local `docker compose exec web yarn test` got
// the tight 5s budget and the heavy form tests timed out (e.g. McpServerFormModal stdio/header
// submits). Only a true bare-metal host run (no /.dockerenv, no CI) keeps the tight ceiling so
// genuine hangs still surface fast there.
//
// Retries are deliberately off everywhere: a suite that only passes on the second attempt is
// hiding a real defect. A flaky test gets fixed, and a genuinely unlucky run gets re-run by hand.
const isSlowRunner = !!process.env.CI || existsSync('/.dockerenv');

export default defineConfig({
  plugins: [tsconfigPaths(), reactSwc()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./app/frontend/test/setup.ts'],
    css: false, // assert behavior/roles, not pixels
    clearMocks: true, // reset spy call history between tests, keep implementations
    testTimeout: isSlowRunner ? 20000 : 5000,
    hookTimeout: isSlowRunner ? 20000 : 10000,
    retry: 0,
    include: ['app/frontend/**/*.{test,spec}.{ts,tsx}'],
    exclude: ['node_modules/**', 'test/playwright/**'],
    coverage: {
      provider: 'v8',
      // separate dir so it never clobbers SimpleCov's output in coverage/
      reportsDirectory: './coverage/frontend',
      reporter: ['text-summary', 'json-summary', 'html'],
      // instrument every included file, not just those imported by a test, so the % is honest
      // across the whole frontend — untested files count as 0% instead of being omitted entirely.
      all: true,
      // count untested source files as 0% so the % reflects the whole frontend
      include: ['app/frontend/**/*.{ts,tsx}'],
      exclude: [
        'app/frontend/**/*.{test,spec}.{ts,tsx}',
        'app/frontend/test/**',
        'app/frontend/types/generated/**',
        'app/frontend/entrypoints/**',
        'app/frontend/**/*.d.ts',
        // generated by ts_routes-rails — not hand-written, not worth testing
        'app/frontend/shared/routes.ts',
      ],
      // Coverage floor, ~1pt under the 2026-07-22 measurement (stmts 71.6 /
      // branch 65.7 / funcs 67.0 / lines 73.7). Only evaluated when coverage
      // runs (check_all / --coverage), so plain `yarn test` stays unaffected.
      // Ratchet upward as coverage grows — never lower.
      thresholds: {
        statements: 71,
        branches: 65,
        functions: 66,
        lines: 73,
      },
    },
  },
});
