import reactSwc from '@vitejs/plugin-react-swc';
import { defineConfig } from 'vitest/config';
import tsconfigPaths from 'vite-tsconfig-paths';

// Dedicated config — intentionally does NOT load ViteRuby()/inertia() from vite.config.ts,
// which assume a live Rails/Inertia context and break under Vitest (vitest#436).
// Keeps tsconfig path aliases (shared/ui, layouts/*, @/types/generated, test/*) and JSX.

// CI runners (2–4 vCPU) run these jsdom + userEvent tests ~6–10× slower than a dev machine —
// with coverage on, the heaviest form-interaction tests (~0.8s locally) brush the default 5s
// ceiling and flake. Give CI generous headroom and retry the occasional contention-driven
// timeout. Locally we keep the tight 5s ceiling and no retries so real hangs surface fast.
const isCI = !!process.env.CI;

export default defineConfig({
  plugins: [tsconfigPaths(), reactSwc()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./app/frontend/test/setup.ts'],
    css: false, // assert behavior/roles, not pixels
    clearMocks: true, // reset spy call history between tests, keep implementations
    testTimeout: isCI ? 20000 : 5000,
    hookTimeout: isCI ? 20000 : 10000,
    retry: isCI ? 2 : 0,
    include: ['app/frontend/**/*.{test,spec}.{ts,tsx}'],
    exclude: ['node_modules/**', 'test/playwright/**'],
    coverage: {
      provider: 'v8',
      // separate dir so it never clobbers SimpleCov's output in coverage/
      reportsDirectory: './coverage/frontend',
      reporter: ['text-summary', 'json-summary', 'html'],
      // instrument every included file, not just those imported by a test, so the % is honest
      // across the whole frontend — untested files count as 0% instead of being omitted entirely.
      all: true,
      // count untested source files as 0% so the % reflects the whole frontend
      include: ['app/frontend/**/*.{ts,tsx}'],
      exclude: [
        'app/frontend/**/*.{test,spec}.{ts,tsx}',
        'app/frontend/test/**',
        'app/frontend/types/generated/**',
        'app/frontend/entrypoints/**',
        'app/frontend/**/*.d.ts',
        // generated by ts_routes-rails — not hand-written, not worth testing
        'app/frontend/shared/routes.ts',
      ],
    },
  },
});
