apiVersion: v1
kind: ConfigMap
metadata:
  name: palad-workflows
  namespace: palad
data:
  workflows.yml: |
    workflows:
      - name: container_workflow
        owner: palad_ruby
        activities:
          - name: container_phase_activity
            task_queue: palad_ruby
