apiVersion: v1
kind: Secret
metadata:
  name: palad-app-secrets
  namespace: palad
type: Opaque
stringData:
  # Replace these values if you use kube-secrets-apply.
  RAILS_SECRET_KEY_BASE: "replace_me"
  # For production, set this to TF_VAR_rds_master_password (or the applied RDS master password).
  DB_PASSWORD: "replace_me"
  GITHUB_PRIVATE_PEM: "replace_me"
  BITBUCKET_OAUTH_SECRET: "replace_me"
  GITLAB_APP_SECRET: "replace_me"
