apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    aixle.com/env: prod
---
# Allow all pods within the monitoring namespace to communicate
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-same-namespace
  namespace: monitoring
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
---
# Allow Traefik (in palad namespace) to reach Grafana and Headlamp
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traefik-to-observability-uis
  namespace: monitoring
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: palad
          podSelector:
            matchLabels:
              app: traefik
