apiVersion: v1
kind: ServiceAccount
metadata:
  name: palad-web
  namespace: palad-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: palad-worker
  namespace: palad-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: palad-otlp
  namespace: palad-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: palad-runtime
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["create", "get", "update"]
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "services"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: ["traefik.io"]
    resources: ["ingressroutes", "middlewares"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: palad-runtime
subjects:
  - kind: ServiceAccount
    name: palad-web
    namespace: palad-dev
  - kind: ServiceAccount
    name: palad-worker
    namespace: palad-dev
  - kind: ServiceAccount
    name: palad-otlp
    namespace: palad-dev
roleRef:
  kind: ClusterRole
  name: palad-runtime
  apiGroup: rbac.authorization.k8s.io
