apiVersion: v1
kind: Secret
metadata:
  name: palad-app-secrets
  namespace: palad
type: Opaque
stringData:
  RAILS_SECRET_KEY_BASE: "secret"
  DB_PASSWORD: "postgres"
  GITHUB_PRIVATE_PEM: "replace_me"
  BITBUCKET_OAUTH_SECRET: "replace_me"
  GITLAB_APP_SECRET: "replace_me"
