apiVersion: v1
kind: ConfigMap
metadata:
  name: palad-app-config
  namespace: palad-dev
data:
  RAILS_ENV: development
  RAILS_PORT: "4000"
  RAILS_LOG_TO_STDOUT: "true"
  ACTION_CABLE_URL: /cable
  DB_HOST: db
  DB_PORT: "5432"
  DB_USERNAME: postgres
  DB_NAME: palad_development
  REDIS_URL: redis://redis:6379/1
  TEMPORAL_ENABLED: "true"
  TEMPORAL_DEBUG: "true"
  TEMPORAL_HOST: temporal
  TEMPORAL_PORT: "7233"
  TEMPORAL_NAMESPACE: default
  TEMPORAL_TASK_QUEUE: palad_ruby
  TEMPORAL_WORKER_GRACEFUL_SHUTDOWN_PERIOD: "900"
  TEMPORAL_UI_URL: https://temporal.k8s.orb.local
  TEMPORAL_DB_HOST: db
  TEMPORAL_DB_PORT: "5432"
  TEMPORAL_DB_USERNAME: postgres
  TEMPORAL_DB_NAME: temporal
  TEMPORAL_VISIBILITY_DB_NAME: temporal_visibility
  TEMPORAL_POSTGRES_TLS_ENABLED: "false"
  TEMPORAL_POSTGRES_TLS_DISABLE_HOST_VERIFICATION: "false"
  TEMPORAL_SQL_TLS: "false"
  TEMPORAL_SQL_HOST_VERIFICATION: "false"
  TRAEFIK_WS_BASE: wss://k8s.orb.local
  TRAEFIK_HTTP_BASE: https://k8s.orb.local
  TRAEFIK_DASHBOARD_URL: https://traefik.k8s.orb.local
  TRAEFIK_CORS_ORIGINS: https://k8s.orb.local
  CONTAINER_ASSET_HOST: "https://k8s.orb.local"
  ASSET_HOST: "https://k8s.orb.local"
  DOMAIN: "k8s.orb.local"
  PROTOCOL: "https"
  CONTAINER_RUNTIME: k8s
  K8S_NAMESPACE: palad-dev
  K8S_IMAGE_PULL_POLICY: IfNotPresent
  MCP_SERVER_URL: "http://mcp.palad-dev.svc.cluster.local:4002/action_mcp"
  MCP_PORT: "4002"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otlp-ingest.palad-dev.svc.cluster.local:4318"
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://otlp-ingest.palad-dev.svc.cluster.local:4318/v1/metrics"
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "http://otlp-ingest.palad-dev.svc.cluster.local:4318/v1/logs"
  GITHUB_CLIENT_ID: "get_from_1password"
  GITHUB_APP_URL: "https://github.com/apps/3po-test-dev-app"
  GITHUB_WEBHOOK_SECRET: "get_from_1password"
  BITBUCKET_OAUTH_KEY: "get_from_1password"
  GITLAB_APP_ID: "get_from_1password"
