apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: palad-dev
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`k8s.orb.local`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: web
          port: 4000
  tls: {}
