apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: palad-staging
  labels:
    palad.ai/runtime-origin: palad-staging
spec:
  entryPoints:
    - websecure
  routes:
    - match: (Host(`staging.aixle.com`) || Host(`www.staging.aixle.com`)) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: staging-basic-auth
      services:
        - name: web
          port: 4000
  tls:
    certResolver: letsencrypt
    domains:
      - main: staging.aixle.com
        sans:
          - www.staging.aixle.com
          - traefik.staging.aixle.com
          - temporal.staging.aixle.com
