apiVersion: apps/v1
kind: Deployment
metadata:
  name: otlp-ingest
  namespace: palad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otlp-ingest
  template:
    metadata:
      labels:
        app: otlp-ingest
    spec:
      serviceAccountName: palad-otlp
      containers:
        - name: otlp-ingest
          image: ghcr.io/palad-ai/palad-app-otlp-ingest:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: palad-app-config
          env:
            - name: OTLP_INGEST_PORT
              value: "4318"
            - name: OTLP_INGEST_WEB_BASE_URL
              value: "http://web:4000"
          ports:
            - name: http
              containerPort: 4318
