#!/usr/bin/env python3
"""Generate constants/workflows.py from config/workflows.yml.

Usage:
    python scripts/generate_workflow_constants.py
"""
import sys
from pathlib import Path

import yaml


def to_class_name(snake_case: str) -> str:
    """Convert snake_case to PascalCase."""
    return "".join(word.capitalize() for word in snake_case.split("_"))


def generate_constants(yaml_path: str, output_path: str) -> None:
    """Generate constants.py from workflows.yml."""

    # Read YAML
    with open(yaml_path, 'r') as f:
        config = yaml.safe_load(f)

    workflows = config.get('workflows', [])

    # Build output
    lines = [
        '"""Workflow constants - AUTO-GENERATED from config/workflows.yml.',
        '',
        'DO NOT EDIT THIS FILE MANUALLY!',
        'Regenerate: python scripts/generate_workflow_constants.py',
        '',
        'Pure Python constants without external dependencies - safe for Temporal sandbox.',
        '"""',
        'from dataclasses import dataclass',
        '',
        '',
        '@dataclass(frozen=True)',
        'class ActivityDef:',
        '    """Activity definition."""',
        '    name: str',
        '    task_queue: str',
        '',
        '',
        '@dataclass(frozen=True)',
        'class ActivitiesCollection:',
        '    """Collection of activities for a workflow."""',
    ]

    # Collect all unique activity names across all workflows
    all_activity_names = set()
    for wf in workflows:
        for act in wf.get('activities', []):
            all_activity_names.add(act['name'])

    # Add activity fields to ActivitiesCollection
    for act_name in sorted(all_activity_names):
        lines.append(f'    {act_name}: ActivityDef | None = None')

    lines.extend(['', ''])

    # WorkflowDef
    lines.extend([
        '@dataclass(frozen=True)',
        'class WorkflowDef:',
        '    """Workflow definition."""',
        '    name: str',
        '    owner: str',
        '    activities: ActivitiesCollection',
        '',
        ''
    ])

    # Generate constants for each workflow
    for wf in workflows:
        wf_name = wf['name']
        wf_const_name = wf_name.upper()
        owner = wf.get('owner', 'palad_python')

        lines.append(f'# Workflow: {wf_name}')
        lines.append(f'{wf_const_name} = WorkflowDef(')
        lines.append(f'    name="{wf_name}",')
        lines.append(f'    owner="{owner}",')
        lines.append('    activities=ActivitiesCollection(')

        # Add activities
        for act in wf.get('activities', []):
            act_name = act['name']
            act_task_queue = act['task_queue']

            lines.append(f'        {act_name}=ActivityDef(')
            lines.append(f'            name="{act_name}",')
            lines.append(f'            task_queue="{act_task_queue}",')
            lines.append('        ),')

        lines.append('    ),')
        lines.append(')')
        lines.append('')

    lines.append('')
    lines.append('# Workflows collection')
    lines.append('class Workflows:')
    lines.append('    """All workflows."""')

    for wf in workflows:
        wf_name = wf['name']
        wf_const_name = wf_name.upper()
        lines.append(f'    {wf_name} = {wf_const_name}')

    lines.append('')

    # Write output
    output = '\n'.join(lines)

    with open(output_path, 'w') as f:
        f.write(output)

    print(f"✅ Generated {output_path}")
    print(f"   {len(workflows)} workflow(s)")


if __name__ == '__main__':
    # Paths
    project_root = Path(__file__).parent.parent
    yaml_path = project_root / 'app' / 'workflows' / 'workflows.yml'
    output_path = project_root / 'app' / 'constants' / 'workflows.py'

    print(f"Reading: {yaml_path}")
    print(f"Writing: {output_path}")
    print()

    if not yaml_path.exists():
        print(f"❌ Error: {yaml_path} not found")
        sys.exit(1)

    generate_constants(str(yaml_path), str(output_path))
