/* tslint:disable */
/* This is generated by ts_routes-rails */

export type ScalarType = string | number | boolean;

function $buildOptions(options: any, names: string[]): string {
  if (options) {
    let anchor = "";
    const q = [] as string[];
    for (const key of Object.keys(options)) {
      if (names.indexOf(key) !== -1) {
        // the key is already consumed
        continue;
      }

      const value = options[key];

      if (key === "anchor") {
        anchor = `#${$encode(value)}`;
      } else {
        $buildQuery(q, key, value);
      }
    }
    return (q.length > 0 ? "?" + q.join("&") : "") + anchor;
  } else {
    return "";
  }
}

function $buildQuery(q: string[], key: string, value: any) {
  if ($isScalarType(value)) {
    q.push(`${$encode(key)}=${$encode(value)}`);
  } else if (Array.isArray(value)) {
    for (const v of value) {
      $buildQuery(q, `${key}[]`, v);
    }
  } else if (value != null) {
    // i.e. non-null, non-scalar, non-array type
    for (const k of Object.keys(value)) {
      $buildQuery(q, `${key}[${k}]`, value[k]);
    }
  }
}

function $encode(value: any): string {
  return encodeURIComponent(value);
}

function $isScalarType(value: any): value is ScalarType {
  return (
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  );
}

function $isPresent(value: any): boolean {
  return value != null && ("" + value).length > 0;
}

function $hasPresentOwnProperty(options: any, key: string): boolean {
  return options && options.hasOwnProperty(key) && $isPresent(options[key]);
}

/** /action_mcp */
export function actionMCPPath(options?: object): string {
  return "/" + "action_mcp" + $buildOptions(options, []);
}

/** /action_mcp/up(.:format) */
export function actionMCPActionMCPHealthCheckPath(options?: object): string {
  return "/" + "action_mcp" + "/" + "up" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /action_mcp/ */
export function actionMCPMCPGetPath(options?: object): string {
  return "/" + "action_mcp" + "/" + $buildOptions(options, []);
}

/** /action_mcp/ */
export function actionMCPMCPPostPath(options?: object): string {
  return "/" + "action_mcp" + "/" + $buildOptions(options, []);
}

/** /action_mcp/ */
export function actionMCPMCPDeletePath(options?: object): string {
  return "/" + "action_mcp" + "/" + $buildOptions(options, []);
}

/** /webhooks/github(.:format) */
export function webhooksGithubPath(options?: object): string {
  return "/" + "webhooks" + "/" + "github" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /webhooks/gitlab(.:format) */
export function webhooksGitlabPath(options?: object): string {
  return "/" + "webhooks" + "/" + "gitlab" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /auth/:provider/callback(.:format) */
export function authCallbackPath(provider: ScalarType, options?: object): string {
  return "/" + "auth" + "/" + provider + "/" + "callback" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["provider","format"]);
}

/** /auth/failure(.:format) */
export function authFailurePath(options?: object): string {
  return "/" + "auth" + "/" + "failure" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/assets/presign(.:format) */
export function presignApiV1AssetsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "assets" + "/" + "presign" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/assets/upload(.:format) */
export function uploadApiV1AssetsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "assets" + "/" + "upload" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/internal/ws_auth(.:format) */
export function apiV1InternalWsAuthPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "internal" + "/" + "ws_auth" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/internal/usage_statistics(.:format) */
export function apiV1InternalUsageStatisticsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "internal" + "/" + "usage_statistics" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/terminal_sessions/:id/finish(.:format) */
export function finishApiV1TerminalSessionPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "terminal_sessions" + "/" + id + "/" + "finish" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/terminal_sessions(.:format) */
export function apiV1TerminalSessionsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "terminal_sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/terminal_sessions/:id(.:format) */
export function apiV1TerminalSessionPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "terminal_sessions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/assets/:id/download(.:format) */
export function downloadApiV1CompanyAssetPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "assets" + "/" + id + "/" + "download" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/assets(.:format) */
export function apiV1CompanyAssetsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/assets/:id(.:format) */
export function apiV1CompanyAssetPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "assets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/workflows/:workflow_id/steps/reorder(.:format) */
export function reorderApiV1WorkflowStepsPath(workflow_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + "/" + "reorder" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["workflow_id","format"]);
}

/** /api/v1/workflows/:workflow_id/steps(.:format) */
export function apiV1WorkflowStepsPath(workflow_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["workflow_id","format"]);
}

/** /api/v1/workflows/:workflow_id/steps/:id(.:format) */
export function apiV1WorkflowStepPath(workflow_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["workflow_id","id","format"]);
}

/** /api/v1/workflows/:id(.:format) */
export function apiV1WorkflowPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "workflows" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/projects/:project_id/assets/:id/download(.:format) */
export function downloadApiV1ProjectAssetPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "assets" + "/" + id + "/" + "download" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/projects/:project_id/assets(.:format) */
export function apiV1ProjectAssetsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/projects/:project_id/assets/:id(.:format) */
export function apiV1ProjectAssetPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "assets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/projects/:project_id/workflows/:workflow_id/steps/reorder(.:format) */
export function reorderApiV1ProjectWorkflowStepsPath(project_id: ScalarType, workflow_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + "/" + "reorder" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_id","format"]);
}

/** /api/v1/projects/:project_id/workflows/:workflow_id/steps(.:format) */
export function apiV1ProjectWorkflowStepsPath(project_id: ScalarType, workflow_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_id","format"]);
}

/** /api/v1/projects/:project_id/workflows/:workflow_id/steps/:id(.:format) */
export function apiV1ProjectWorkflowStepPath(project_id: ScalarType, workflow_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_id","id","format"]);
}

/** /api/v1/projects/:project_id/workflows/:id(.:format) */
export function apiV1ProjectWorkflowPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/projects/:project_id/workflow_runs/:workflow_run_id/workflow_run_assets/:id/export(.:format) */
export function exportApiV1ProjectWorkflowRunWorkflowRunAssetPath(project_id: ScalarType, workflow_run_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + workflow_run_id + "/" + "workflow_run_assets" + "/" + id + "/" + "export" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_run_id","id","format"]);
}

/** /api/v1/projects/:project_id/workflow_runs/:workflow_run_id/workflow_run_assets/:id/download(.:format) */
export function downloadApiV1ProjectWorkflowRunWorkflowRunAssetPath(project_id: ScalarType, workflow_run_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + workflow_run_id + "/" + "workflow_run_assets" + "/" + id + "/" + "download" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_run_id","id","format"]);
}

/** /api/v1/projects/:project_id/workflow_runs/:workflow_run_id/workflow_run_assets/export_all(.:format) */
export function exportAllApiV1ProjectWorkflowRunWorkflowRunAssetsPath(project_id: ScalarType, workflow_run_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + workflow_run_id + "/" + "workflow_run_assets" + "/" + "export_all" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_run_id","format"]);
}

/** /api/v1/projects/:project_id/workflow_runs/:workflow_run_id/workflow_run_assets(.:format) */
export function apiV1ProjectWorkflowRunWorkflowRunAssetsPath(project_id: ScalarType, workflow_run_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + workflow_run_id + "/" + "workflow_run_assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_run_id","format"]);
}

/** /api/v1/projects/:project_id/board(.:format) */
export function apiV1ProjectBoardPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "board" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/projects/:project_id/view_presets(.:format) */
export function apiV1ProjectViewPresetsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "view_presets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/projects/:project_id/view_presets/:id(.:format) */
export function apiV1ProjectViewPresetPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "view_presets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/projects/:project_id/columns/reorder(.:format) */
export function reorderApiV1ProjectColumnsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "columns" + "/" + "reorder" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/projects/:project_id/columns/:column_id/workflow_binding(.:format) */
export function apiV1ProjectColumnWorkflowBindingPath(project_id: ScalarType, column_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "columns" + "/" + column_id + "/" + "workflow_binding" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","column_id","format"]);
}

/** /api/v1/projects/:project_id/columns(.:format) */
export function apiV1ProjectColumnsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "columns" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/projects/:project_id/columns/new(.:format) */
export function newApiV1ProjectColumnPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "columns" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/projects/:project_id/columns/:id/edit(.:format) */
export function editApiV1ProjectColumnPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "columns" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/projects/:project_id/columns/:id(.:format) */
export function apiV1ProjectColumnPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "columns" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/projects/:project_id/activities(.:format) */
export function apiV1ProjectActivitiesPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "activities" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/projects/:project_id/tasks/:id/move(.:format) */
export function moveApiV1ProjectTaskPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "tasks" + "/" + id + "/" + "move" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/projects/:project_id/tasks/:id/trigger_workflow(.:format) */
export function triggerWorkflowApiV1ProjectTaskPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "tasks" + "/" + id + "/" + "trigger_workflow" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/projects/:project_id/tasks/:id/workflow_runs(.:format) */
export function workflowRunsApiV1ProjectTaskPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "tasks" + "/" + id + "/" + "workflow_runs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/projects/:project_id/tasks/:task_id/comments(.:format) */
export function apiV1ProjectTaskCommentsPath(project_id: ScalarType, task_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "tasks" + "/" + task_id + "/" + "comments" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","task_id","format"]);
}

/** /api/v1/projects/:project_id/tasks/:task_id/assets(.:format) */
export function apiV1ProjectTaskAssetsPath(project_id: ScalarType, task_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "tasks" + "/" + task_id + "/" + "assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","task_id","format"]);
}

/** /api/v1/projects/:project_id/tasks/:task_id/assets/:id(.:format) */
export function apiV1ProjectTaskAssetPath(project_id: ScalarType, task_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "tasks" + "/" + task_id + "/" + "assets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","task_id","id","format"]);
}

/** /api/v1/projects/:project_id/tasks/:task_id/waits/:id(.:format) */
export function apiV1ProjectTaskWaitPath(project_id: ScalarType, task_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "tasks" + "/" + task_id + "/" + "waits" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","task_id","id","format"]);
}

/** /api/v1/projects/:project_id/tasks/:task_id/transitions(.:format) */
export function apiV1ProjectTaskTransitionsPath(project_id: ScalarType, task_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "tasks" + "/" + task_id + "/" + "transitions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","task_id","format"]);
}

/** /api/v1/projects/:project_id/tasks/:task_id/activities(.:format) */
export function apiV1ProjectTaskActivitiesPath(project_id: ScalarType, task_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "tasks" + "/" + task_id + "/" + "activities" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","task_id","format"]);
}

/** /api/v1/projects/:project_id/tasks/:task_id/statistics(.:format) */
export function apiV1ProjectTaskStatisticsPath(project_id: ScalarType, task_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "tasks" + "/" + task_id + "/" + "statistics" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","task_id","format"]);
}

/** /api/v1/projects/:project_id/tasks(.:format) */
export function apiV1ProjectTasksPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "tasks" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/projects/:project_id/tasks/new(.:format) */
export function newApiV1ProjectTaskPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "tasks" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/projects/:project_id/tasks/:id/edit(.:format) */
export function editApiV1ProjectTaskPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "tasks" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/projects/:project_id/tasks/:id(.:format) */
export function apiV1ProjectTaskPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "projects" + "/" + project_id + "/" + "tasks" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /admin(.:format) */
export function adminRootPath(options?: object): string {
  return "/" + "admin" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/users/:id/impersonate(.:format) */
export function impersonateAdminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + "/" + "impersonate" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/users/:id/stop_impersonate(.:format) */
export function stopImpersonateAdminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + "/" + "stop_impersonate" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/users(.:format) */
export function adminUsersPath(options?: object): string {
  return "/" + "admin" + "/" + "users" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/users/new(.:format) */
export function newAdminUserPath(options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/users/:id/edit(.:format) */
export function editAdminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/users/:id(.:format) */
export function adminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/companies(.:format) */
export function adminCompaniesPath(options?: object): string {
  return "/" + "admin" + "/" + "companies" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/companies/new(.:format) */
export function newAdminCompanyPath(options?: object): string {
  return "/" + "admin" + "/" + "companies" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/companies/:id/edit(.:format) */
export function editAdminCompanyPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "companies" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/companies/:id(.:format) */
export function adminCompanyPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "companies" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/projects(.:format) */
export function adminProjectsPath(options?: object): string {
  return "/" + "admin" + "/" + "projects" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/projects/new(.:format) */
export function newAdminProjectPath(options?: object): string {
  return "/" + "admin" + "/" + "projects" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/projects/:id/edit(.:format) */
export function editAdminProjectPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "projects" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/projects/:id(.:format) */
export function adminProjectPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "projects" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/project_collaborators(.:format) */
export function adminProjectCollaboratorsPath(options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/project_collaborators/new(.:format) */
export function newAdminProjectCollaboratorPath(options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/project_collaborators/:id/edit(.:format) */
export function editAdminProjectCollaboratorPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/project_collaborators/:id(.:format) */
export function adminProjectCollaboratorPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/agent_credentials(.:format) */
export function adminAgentCredentialsPath(options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/agent_credentials/new(.:format) */
export function newAdminAgentCredentialPath(options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/agent_credentials/:id/edit(.:format) */
export function editAdminAgentCredentialPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/agent_credentials/:id(.:format) */
export function adminAgentCredentialPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/terminal_sessions(.:format) */
export function adminTerminalSessionsPath(options?: object): string {
  return "/" + "admin" + "/" + "terminal_sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/terminal_sessions/:id(.:format) */
export function adminTerminalSessionPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "terminal_sessions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/session_logs(.:format) */
export function adminSessionLogsPath(options?: object): string {
  return "/" + "admin" + "/" + "session_logs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/session_logs/:id(.:format) */
export function adminSessionLogPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "session_logs" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/assets(.:format) */
export function adminAssetsPath(options?: object): string {
  return "/" + "admin" + "/" + "assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/assets/:id(.:format) */
export function adminAssetPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "assets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/asset_versions(.:format) */
export function adminAssetVersionsPath(options?: object): string {
  return "/" + "admin" + "/" + "asset_versions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/asset_versions/:id(.:format) */
export function adminAssetVersionPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "asset_versions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/tool_results(.:format) */
export function adminToolResultsPath(options?: object): string {
  return "/" + "admin" + "/" + "tool_results" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/tool_results/:id(.:format) */
export function adminToolResultPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "tool_results" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/contact_requests(.:format) */
export function adminContactRequestsPath(options?: object): string {
  return "/" + "admin" + "/" + "contact_requests" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/contact_requests/:id(.:format) */
export function adminContactRequestPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "contact_requests" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/agents(.:format) */
export function adminAgentsPath(options?: object): string {
  return "/" + "admin" + "/" + "agents" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/agents/:id(.:format) */
export function adminAgentPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "agents" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/boards(.:format) */
export function adminBoardsPath(options?: object): string {
  return "/" + "admin" + "/" + "boards" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/boards/:id(.:format) */
export function adminBoardPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "boards" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/board_activities(.:format) */
export function adminBoardActivitiesPath(options?: object): string {
  return "/" + "admin" + "/" + "board_activities" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/board_activities/:id(.:format) */
export function adminBoardActivityPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "board_activities" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/board_columns(.:format) */
export function adminBoardColumnsPath(options?: object): string {
  return "/" + "admin" + "/" + "board_columns" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/board_columns/:id(.:format) */
export function adminBoardColumnPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "board_columns" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/board_tasks(.:format) */
export function adminBoardTasksPath(options?: object): string {
  return "/" + "admin" + "/" + "board_tasks" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/board_tasks/:id(.:format) */
export function adminBoardTaskPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "board_tasks" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/board_view_presets(.:format) */
export function adminBoardViewPresetsPath(options?: object): string {
  return "/" + "admin" + "/" + "board_view_presets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/board_view_presets/:id(.:format) */
export function adminBoardViewPresetPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "board_view_presets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/column_transitions(.:format) */
export function adminColumnTransitionsPath(options?: object): string {
  return "/" + "admin" + "/" + "column_transitions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/column_transitions/:id(.:format) */
export function adminColumnTransitionPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "column_transitions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/column_workflow_bindings(.:format) */
export function adminColumnWorkflowBindingsPath(options?: object): string {
  return "/" + "admin" + "/" + "column_workflow_bindings" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/column_workflow_bindings/:id(.:format) */
export function adminColumnWorkflowBindingPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "column_workflow_bindings" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/config_items(.:format) */
export function adminConfigItemsPath(options?: object): string {
  return "/" + "admin" + "/" + "config_items" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/config_items/:id(.:format) */
export function adminConfigItemPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "config_items" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/integrations(.:format) */
export function adminIntegrationsPath(options?: object): string {
  return "/" + "admin" + "/" + "integrations" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/integrations/:id(.:format) */
export function adminIntegrationPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "integrations" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/mcp_servers(.:format) */
export function adminMCPServersPath(options?: object): string {
  return "/" + "admin" + "/" + "mcp_servers" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/mcp_servers/:id(.:format) */
export function adminMCPServerPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "mcp_servers" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/repositories(.:format) */
export function adminRepositoriesPath(options?: object): string {
  return "/" + "admin" + "/" + "repositories" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/repositories/:id(.:format) */
export function adminRepositoryPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "repositories" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/skills(.:format) */
export function adminSkillsPath(options?: object): string {
  return "/" + "admin" + "/" + "skills" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/skills/:id(.:format) */
export function adminSkillPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "skills" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/tools(.:format) */
export function adminToolsPath(options?: object): string {
  return "/" + "admin" + "/" + "tools" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/tools/:id(.:format) */
export function adminToolPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "tools" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/tool_files(.:format) */
export function adminToolFilesPath(options?: object): string {
  return "/" + "admin" + "/" + "tool_files" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/tool_files/:id(.:format) */
export function adminToolFilePath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "tool_files" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/workflows(.:format) */
export function adminWorkflowsPath(options?: object): string {
  return "/" + "admin" + "/" + "workflows" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/workflows/:id(.:format) */
export function adminWorkflowPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "workflows" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/workflow_runs(.:format) */
export function adminWorkflowRunsPath(options?: object): string {
  return "/" + "admin" + "/" + "workflow_runs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/workflow_runs/:id(.:format) */
export function adminWorkflowRunPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "workflow_runs" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/workflow_run_assets(.:format) */
export function adminWorkflowRunAssetsPath(options?: object): string {
  return "/" + "admin" + "/" + "workflow_run_assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/workflow_run_assets/:id(.:format) */
export function adminWorkflowRunAssetPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "workflow_run_assets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/steps(.:format) */
export function adminStepsPath(options?: object): string {
  return "/" + "admin" + "/" + "steps" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/steps/:id(.:format) */
export function adminStepPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "steps" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/step_runs(.:format) */
export function adminStepRunsPath(options?: object): string {
  return "/" + "admin" + "/" + "step_runs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/step_runs/:id(.:format) */
export function adminStepRunPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "step_runs" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/sub_steps(.:format) */
export function adminSubStepsPath(options?: object): string {
  return "/" + "admin" + "/" + "sub_steps" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/sub_steps/:id(.:format) */
export function adminSubStepPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "sub_steps" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/sub_step_runs(.:format) */
export function adminSubStepRunsPath(options?: object): string {
  return "/" + "admin" + "/" + "sub_step_runs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/sub_step_runs/:id(.:format) */
export function adminSubStepRunPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "sub_step_runs" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/task_comments(.:format) */
export function adminTaskCommentsPath(options?: object): string {
  return "/" + "admin" + "/" + "task_comments" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/task_comments/:id(.:format) */
export function adminTaskCommentPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "task_comments" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/task_assets(.:format) */
export function adminTaskAssetsPath(options?: object): string {
  return "/" + "admin" + "/" + "task_assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/task_assets/:id(.:format) */
export function adminTaskAssetPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "task_assets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/usage_statistics(.:format) */
export function adminUsageStatisticsPath(options?: object): string {
  return "/" + "admin" + "/" + "usage_statistics" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/usage_statistics/:id(.:format) */
export function adminUsageStatisticPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "usage_statistics" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/namespace_resource_quotas(.:format) */
export function adminNamespaceResourceQuotasPath(options?: object): string {
  return "/" + "admin" + "/" + "namespace_resource_quotas" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/namespace_resource_quotas/new(.:format) */
export function newAdminNamespaceResourceQuotaPath(options?: object): string {
  return "/" + "admin" + "/" + "namespace_resource_quotas" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/namespace_resource_quotas/:id/edit(.:format) */
export function editAdminNamespaceResourceQuotaPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "namespace_resource_quotas" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/namespace_resource_quotas/:id(.:format) */
export function adminNamespaceResourceQuotaPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "namespace_resource_quotas" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** / */
export function rootPath(options?: object): string {
  return "/" + $buildOptions(options, []);
}

/** /docs */
export function oasRailsPath(options?: object): string {
  return "/" + "docs" + $buildOptions(options, []);
}

/** /letter_opener */
export function letterOpenerWebPath(options?: object): string {
  return "/" + "letter_opener" + $buildOptions(options, []);
}

/** /letter_opener/ */
export function letterOpenerWebLettersPath(options?: object): string {
  return "/" + "letter_opener" + "/" + $buildOptions(options, []);
}

/** /letter_opener/clear(.:format) */
export function letterOpenerWebClearLettersPath(options?: object): string {
  return "/" + "letter_opener" + "/" + "clear" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /letter_opener/:id(/:style)(.:format) */
export function letterOpenerWebLetterPath(id: ScalarType, options?: object): string {
  return "/" + "letter_opener" + "/" + id + ($hasPresentOwnProperty(options, "style") ? "/" + (options as any).style : "") + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","style","format"]);
}

/** /letter_opener/:id/delete(.:format) */
export function letterOpenerWebDeleteLetterPath(id: ScalarType, options?: object): string {
  return "/" + "letter_opener" + "/" + id + "/" + "delete" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /login(.:format) */
export function loginPath(options?: object): string {
  return "/" + "login" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /logout(.:format) */
export function logoutPath(options?: object): string {
  return "/" + "logout" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /privacy-policy(.:format) */
export function privacyPolicyPath(options?: object): string {
  return "/" + "privacy-policy" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /terms-of-service(.:format) */
export function termsOfServicePath(options?: object): string {
  return "/" + "terms-of-service" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /profile/update_default_model(.:format) */
export function updateDefaultModelProfilePath(options?: object): string {
  return "/" + "profile" + "/" + "update_default_model" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /profile/destroy_credential(.:format) */
export function destroyCredentialProfilePath(options?: object): string {
  return "/" + "profile" + "/" + "destroy_credential" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /profile(.:format) */
export function profilePath(options?: object): string {
  return "/" + "profile" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /onboarding(.:format) */
export function onboardingPath(options?: object): string {
  return "/" + "onboarding" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/members(.:format) */
export function companyMembersPath(options?: object): string {
  return "/" + "company" + "/" + "members" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/members/:id(.:format) */
export function companyMemberPath(id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "members" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /company/config_items(.:format) */
export function companyConfigItemsPath(options?: object): string {
  return "/" + "company" + "/" + "config_items" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/config_items/:id(.:format) */
export function companyConfigItemPath(id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "config_items" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /company/integrations/github_setup(.:format) */
export function githubSetupCompanyIntegrationsPath(options?: object): string {
  return "/" + "company" + "/" + "integrations" + "/" + "github_setup" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/integrations(.:format) */
export function companyIntegrationsPath(options?: object): string {
  return "/" + "company" + "/" + "integrations" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/integrations/:id(.:format) */
export function companyIntegrationPath(id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "integrations" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /company/repositories(.:format) */
export function companyRepositoriesPath(options?: object): string {
  return "/" + "company" + "/" + "repositories" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/repositories/:id(.:format) */
export function companyRepositoryPath(id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "repositories" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /company/projects/:project_id/overview(.:format) */
export function companyProjectOverviewIndexPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "overview" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/board(.:format) */
export function companyProjectBoardPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/sessions/:session_id/artifacts/review(.:format) */
export function reviewCompanyProjectSessionArtifactsPath(project_id: ScalarType, session_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "sessions" + "/" + session_id + "/" + "artifacts" + "/" + "review" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","session_id","format"]);
}

/** /company/projects/:project_id/sessions/:session_id/artifacts(.:format) */
export function companyProjectSessionArtifactsPath(project_id: ScalarType, session_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "sessions" + "/" + session_id + "/" + "artifacts" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","session_id","format"]);
}

/** /company/projects/:project_id/sessions(.:format) */
export function companyProjectSessionsPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/sessions/new(.:format) */
export function newCompanyProjectSessionPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "sessions" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/sessions/:id(.:format) */
export function companyProjectSessionPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "sessions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/workflows/from_template(.:format) */
export function fromTemplateCompanyProjectWorkflowsPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + "from_template" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/workflows/:id/builder(.:format) */
export function builderCompanyProjectWorkflowPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + id + "/" + "builder" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/workflows/:id/duplicate(.:format) */
export function duplicateCompanyProjectWorkflowPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + id + "/" + "duplicate" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/workflows(.:format) */
export function companyProjectWorkflowsPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/workflows/:id(.:format) */
export function companyProjectWorkflowPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/workflow_runs/:id/cancel(.:format) */
export function cancelCompanyProjectWorkflowRunPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + id + "/" + "cancel" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/workflow_runs/:id/approve_step(.:format) */
export function approveStepCompanyProjectWorkflowRunPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + id + "/" + "approve_step" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/workflow_runs/:id/retry_step(.:format) */
export function retryStepCompanyProjectWorkflowRunPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + id + "/" + "retry_step" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/workflow_runs/:id/skip_step(.:format) */
export function skipStepCompanyProjectWorkflowRunPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + id + "/" + "skip_step" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/workflow_runs(.:format) */
export function companyProjectWorkflowRunsPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/workflow_runs/:id(.:format) */
export function companyProjectWorkflowRunPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/aixle_builder(.:format) */
export function companyProjectAixleBuilderPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "aixle_builder" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/aixle_builder/start(.:format) */
export function companyProjectAixleBuilderStartPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "aixle_builder" + "/" + "start" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/aixle_builder/:id/session(.:format) */
export function companyProjectAixleBuilderSessionPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "aixle_builder" + "/" + id + "/" + "session" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/aixle_builder/:id/finish(.:format) */
export function companyProjectAixleBuilderFinishPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "aixle_builder" + "/" + id + "/" + "finish" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/assets(.:format) */
export function companyProjectAssetsPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/analytics(.:format) */
export function companyProjectAnalyticsPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "analytics" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/repositories(.:format) */
export function companyProjectRepositoriesPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "repositories" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/repositories/:id(.:format) */
export function companyProjectRepositoryPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "repositories" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/integrations(.:format) */
export function companyProjectIntegrationsPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "integrations" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/integrations/:id(.:format) */
export function companyProjectIntegrationPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "integrations" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/agents(.:format) */
export function companyProjectAgentsPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "agents" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/agents/:id(.:format) */
export function companyProjectAgentPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "agents" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/tools(.:format) */
export function companyProjectToolsPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "tools" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/tools/:id(.:format) */
export function companyProjectToolPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "tools" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/mcp_servers(.:format) */
export function companyProjectMCPServersPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "mcp_servers" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/mcp_servers/:id(.:format) */
export function companyProjectMCPServerPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "mcp_servers" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/skills(.:format) */
export function companyProjectSkillsPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "skills" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/skills/:id(.:format) */
export function companyProjectSkillPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "skills" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/config_items(.:format) */
export function companyProjectConfigItemsPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "config_items" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/config_items/:id(.:format) */
export function companyProjectConfigItemPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "config_items" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/members(.:format) */
export function companyProjectMembersPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "members" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects/:project_id/members/:id(.:format) */
export function companyProjectMemberPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "members" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /company/projects/:project_id/settings(.:format) */
export function companyProjectSettingsPath(project_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "settings" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /company/projects(.:format) */
export function companyProjectsPath(options?: object): string {
  return "/" + "company" + "/" + "projects" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/projects/:id(.:format) */
export function companyProjectPath(id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "projects" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /company/agents(.:format) */
export function companyAgentsPath(options?: object): string {
  return "/" + "company" + "/" + "agents" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/agents/:id(.:format) */
export function companyAgentPath(id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "agents" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /company/tools(.:format) */
export function companyToolsPath(options?: object): string {
  return "/" + "company" + "/" + "tools" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/tools/:id(.:format) */
export function companyToolPath(id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "tools" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /company/skills(.:format) */
export function companySkillsPath(options?: object): string {
  return "/" + "company" + "/" + "skills" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/skills/:id(.:format) */
export function companySkillPath(id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "skills" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /company/mcp_servers(.:format) */
export function companyMCPServersPath(options?: object): string {
  return "/" + "company" + "/" + "mcp_servers" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/mcp_servers/:id(.:format) */
export function companyMCPServerPath(id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "mcp_servers" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /company/workflows/:id/builder(.:format) */
export function builderCompanyWorkflowPath(id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "workflows" + "/" + id + "/" + "builder" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /company/workflows(.:format) */
export function companyWorkflowsPath(options?: object): string {
  return "/" + "company" + "/" + "workflows" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/workflows/:id(.:format) */
export function companyWorkflowPath(id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "workflows" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /company/workflow_templates/:id/publish_version(.:format) */
export function publishVersionCompanyWorkflowTemplatePath(id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "workflow_templates" + "/" + id + "/" + "publish_version" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /company/workflow_templates(.:format) */
export function companyWorkflowTemplatesPath(options?: object): string {
  return "/" + "company" + "/" + "workflow_templates" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/workflow_templates/:id(.:format) */
export function companyWorkflowTemplatePath(id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "workflow_templates" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /company/analytics(.:format) */
export function companyAnalyticsPath(options?: object): string {
  return "/" + "company" + "/" + "analytics" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/assets(.:format) */
export function companyAssetsPath(options?: object): string {
  return "/" + "company" + "/" + "assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/sessions/:session_id/artifacts/review(.:format) */
export function reviewCompanySessionArtifactsPath(session_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "sessions" + "/" + session_id + "/" + "artifacts" + "/" + "review" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["session_id","format"]);
}

/** /company/sessions/:session_id/artifacts(.:format) */
export function companySessionArtifactsPath(session_id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "sessions" + "/" + session_id + "/" + "artifacts" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["session_id","format"]);
}

/** /company/sessions(.:format) */
export function companySessionsPath(options?: object): string {
  return "/" + "company" + "/" + "sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/sessions/new(.:format) */
export function newCompanySessionPath(options?: object): string {
  return "/" + "company" + "/" + "sessions" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /company/sessions/:id(.:format) */
export function companySessionPath(id: ScalarType, options?: object): string {
  return "/" + "company" + "/" + "sessions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}
