export enum QueryTag {
  CurrentUser = 'CurrentUser',
  AgentCredentials = 'AgentCredentials',
  TerminalSession = 'TerminalSession',
  Project = 'Project',
  ProjectCollaborators = 'ProjectCollaborators',
  Workflow = 'Workflow',
  WorkflowRun = 'WorkflowRun',
  Task = 'Task',
  CompanyUsers = 'CompanyUsers',
  ConfigItems = 'ConfigItems',
  Agents = 'Agents',
  Tools = 'Tools',
  McpServers = 'McpServers',
  Skills = 'Skills',
  Assets = 'Assets',
  Integrations = 'Integrations',
  Repositories = 'Repositories',
  Activity = 'Activity',
  ViewPreset = 'ViewPreset',
  Comment = 'Comment',
  TaskAsset = 'TaskAsset',
  PlatformSummary = 'PlatformSummary',
  ProjectAnalytics = 'ProjectAnalytics',
  WorkflowRunStats = 'WorkflowRunStats',
  WorkflowCostAnalytics = 'WorkflowCostAnalytics',
}
