/* tslint:disable */
/* This is generated by ts_routes-rails */

export type ScalarType = string | number | boolean;

function $buildOptions(options: any, names: string[]): string {
  if (options) {
    let anchor = "";
    const q = [] as string[];
    for (const key of Object.keys(options)) {
      if (names.indexOf(key) !== -1) {
        // the key is already consumed
        continue;
      }

      const value = options[key];

      if (key === "anchor") {
        anchor = `#${$encode(value)}`;
      } else {
        $buildQuery(q, key, value);
      }
    }
    return (q.length > 0 ? "?" + q.join("&") : "") + anchor;
  } else {
    return "";
  }
}

function $buildQuery(q: string[], key: string, value: any) {
  if ($isScalarType(value)) {
    q.push(`${$encode(key)}=${$encode(value)}`);
  } else if (Array.isArray(value)) {
    for (const v of value) {
      $buildQuery(q, `${key}[]`, v);
    }
  } else if (value != null) {
    // i.e. non-null, non-scalar, non-array type
    for (const k of Object.keys(value)) {
      $buildQuery(q, `${key}[${k}]`, value[k]);
    }
  }
}

function $encode(value: any): string {
  return encodeURIComponent(value);
}

function $isScalarType(value: any): value is ScalarType {
  return (
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  );
}

function $isPresent(value: any): boolean {
  return value != null && ("" + value).length > 0;
}

function $hasPresentOwnProperty(options: any, key: string): boolean {
  return options && options.hasOwnProperty(key) && $isPresent(options[key]);
}

/** /action_mcp */
export function actionMCPPath(options?: object): string {
  return "/" + "action_mcp" + $buildOptions(options, []);
}

/** /action_mcp/up(.:format) */
export function actionMCPActionMCPHealthCheckPath(options?: object): string {
  return "/" + "action_mcp" + "/" + "up" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /action_mcp/ */
export function actionMCPMCPGetPath(options?: object): string {
  return "/" + "action_mcp" + "/" + $buildOptions(options, []);
}

/** /action_mcp/ */
export function actionMCPMCPPostPath(options?: object): string {
  return "/" + "action_mcp" + "/" + $buildOptions(options, []);
}

/** /action_mcp/ */
export function actionMCPMCPDeletePath(options?: object): string {
  return "/" + "action_mcp" + "/" + $buildOptions(options, []);
}

/** /webhooks/github(.:format) */
export function webhooksGithubPath(options?: object): string {
  return "/" + "webhooks" + "/" + "github" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /webhooks/gitlab(.:format) */
export function webhooksGitlabPath(options?: object): string {
  return "/" + "webhooks" + "/" + "gitlab" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/auth/:provider(.:format) */
export function apiV1AuthPath(provider: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "auth" + "/" + provider + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["provider","format"]);
}

/** /api/v1/auth/:provider/callback(.:format) */
export function apiV1AuthCallbackPath(provider: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "auth" + "/" + provider + "/" + "callback" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["provider","format"]);
}

/** /api/v1/auth/failure(.:format) */
export function apiV1AuthFailurePath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "auth" + "/" + "failure" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/sessions(.:format) */
export function apiV1SessionsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/current_user(.:format) */
export function apiV1CurrentUserPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "current_user" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/agent_models/update_default(.:format) */
export function updateDefaultApiV1AgentModelsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "agent_models" + "/" + "update_default" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/agent_models(.:format) */
export function apiV1AgentModelsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "agent_models" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/contact_requests(.:format) */
export function apiV1ContactRequestsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "contact_requests" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/assets/presign(.:format) */
export function presignApiV1AssetsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "assets" + "/" + "presign" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/assets/upload(.:format) */
export function uploadApiV1AssetsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "assets" + "/" + "upload" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/terminal_sessions/:id/finish(.:format) */
export function finishApiV1TerminalSessionPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "terminal_sessions" + "/" + id + "/" + "finish" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/terminal_sessions(.:format) */
export function apiV1TerminalSessionsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "terminal_sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/terminal_sessions/:id(.:format) */
export function apiV1TerminalSessionPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "terminal_sessions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/internal/ws_auth(.:format) */
export function apiV1InternalWsAuthPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "internal" + "/" + "ws_auth" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/internal/usage_statistics(.:format) */
export function apiV1InternalUsageStatisticsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "internal" + "/" + "usage_statistics" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/integrations/github_setup(.:format) */
export function githubSetupApiV1CompanyIntegrationsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "integrations" + "/" + "github_setup" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/integrations(.:format) */
export function apiV1CompanyIntegrationsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "integrations" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/integrations/:id(.:format) */
export function apiV1CompanyIntegrationPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "integrations" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/users(.:format) */
export function apiV1CompanyUsersPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "users" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/users/:id(.:format) */
export function apiV1CompanyUserPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "users" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/config_items(.:format) */
export function apiV1CompanyConfigItemsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "config_items" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/config_items/:id(.:format) */
export function apiV1CompanyConfigItemPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "config_items" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/agents(.:format) */
export function apiV1CompanyAgentsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "agents" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/agents/:id(.:format) */
export function apiV1CompanyAgentPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "agents" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/tools(.:format) */
export function apiV1CompanyToolsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "tools" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/tools/:id(.:format) */
export function apiV1CompanyToolPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "tools" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/mcp_servers(.:format) */
export function apiV1CompanyMCPServersPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "mcp_servers" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/mcp_servers/:id(.:format) */
export function apiV1CompanyMCPServerPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "mcp_servers" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/skills(.:format) */
export function apiV1CompanySkillsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "skills" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/skills/:id(.:format) */
export function apiV1CompanySkillPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "skills" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/workflows/:workflow_id/steps/reorder(.:format) */
export function reorderApiV1CompanyWorkflowStepsPath(workflow_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + "/" + "reorder" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["workflow_id","format"]);
}

/** /api/v1/company/workflows/:workflow_id/steps(.:format) */
export function apiV1CompanyWorkflowStepsPath(workflow_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["workflow_id","format"]);
}

/** /api/v1/company/workflows/:workflow_id/steps/:id(.:format) */
export function apiV1CompanyWorkflowStepPath(workflow_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["workflow_id","id","format"]);
}

/** /api/v1/company/workflows(.:format) */
export function apiV1CompanyWorkflowsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "workflows" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/workflows/:id(.:format) */
export function apiV1CompanyWorkflowPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "workflows" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/repositories/available(.:format) */
export function availableApiV1CompanyRepositoriesPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "repositories" + "/" + "available" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/repositories/branches(.:format) */
export function branchesApiV1CompanyRepositoriesPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "repositories" + "/" + "branches" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/repositories(.:format) */
export function apiV1CompanyRepositoriesPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "repositories" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/repositories/:id(.:format) */
export function apiV1CompanyRepositoryPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "repositories" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/assets/:id/download(.:format) */
export function downloadApiV1CompanyAssetPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "assets" + "/" + id + "/" + "download" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/assets/:id/versions(.:format) */
export function versionsApiV1CompanyAssetPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "assets" + "/" + id + "/" + "versions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/assets/:id/restore(.:format) */
export function restoreApiV1CompanyAssetPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "assets" + "/" + id + "/" + "restore" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/assets(.:format) */
export function apiV1CompanyAssetsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/assets/:id(.:format) */
export function apiV1CompanyAssetPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "assets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/terminal_sessions/:terminal_session_id/artifacts/review(.:format) */
export function reviewApiV1CompanyTerminalSessionArtifactsPath(terminal_session_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "terminal_sessions" + "/" + terminal_session_id + "/" + "artifacts" + "/" + "review" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["terminal_session_id","format"]);
}

/** /api/v1/company/terminal_sessions/:terminal_session_id/artifacts/:id/download(.:format) */
export function downloadApiV1CompanyTerminalSessionArtifactPath(terminal_session_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "terminal_sessions" + "/" + terminal_session_id + "/" + "artifacts" + "/" + id + "/" + "download" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["terminal_session_id","id","format"]);
}

/** /api/v1/company/terminal_sessions/:terminal_session_id/artifacts(.:format) */
export function apiV1CompanyTerminalSessionArtifactsPath(terminal_session_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "terminal_sessions" + "/" + terminal_session_id + "/" + "artifacts" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["terminal_session_id","format"]);
}

/** /api/v1/company/terminal_sessions(.:format) */
export function apiV1CompanyTerminalSessionsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "terminal_sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/terminal_sessions/:id(.:format) */
export function apiV1CompanyTerminalSessionPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "terminal_sessions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/projects/:project_id/collaborators(.:format) */
export function apiV1CompanyProjectCollaboratorsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "collaborators" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/collaborators/:id(.:format) */
export function apiV1CompanyProjectCollaboratorPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "collaborators" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/config_items(.:format) */
export function apiV1CompanyProjectConfigItemsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "config_items" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/config_items/:id(.:format) */
export function apiV1CompanyProjectConfigItemPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "config_items" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/agents(.:format) */
export function apiV1CompanyProjectAgentsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "agents" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/agents/:id(.:format) */
export function apiV1CompanyProjectAgentPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "agents" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/tools(.:format) */
export function apiV1CompanyProjectToolsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "tools" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/tools/:id(.:format) */
export function apiV1CompanyProjectToolPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "tools" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/mcp_servers(.:format) */
export function apiV1CompanyProjectMCPServersPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "mcp_servers" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/mcp_servers/:id(.:format) */
export function apiV1CompanyProjectMCPServerPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "mcp_servers" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/integrations(.:format) */
export function apiV1CompanyProjectIntegrationsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "integrations" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/integrations/:id(.:format) */
export function apiV1CompanyProjectIntegrationPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "integrations" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/skills(.:format) */
export function apiV1CompanyProjectSkillsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "skills" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/skills/:id(.:format) */
export function apiV1CompanyProjectSkillPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "skills" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/palad_builder/start(.:format) */
export function startApiV1CompanyProjectPaladBuilderPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "palad_builder" + "/" + "start" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/palad_builder/status(.:format) */
export function statusApiV1CompanyProjectPaladBuilderPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "palad_builder" + "/" + "status" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/workflows/:id/duplicate(.:format) */
export function duplicateApiV1CompanyProjectWorkflowPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + id + "/" + "duplicate" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflows/:workflow_id/steps/reorder(.:format) */
export function reorderApiV1CompanyProjectWorkflowStepsPath(project_id: ScalarType, workflow_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + "/" + "reorder" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_id","format"]);
}

/** /api/v1/company/projects/:project_id/workflows/:workflow_id/steps(.:format) */
export function apiV1CompanyProjectWorkflowStepsPath(project_id: ScalarType, workflow_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_id","format"]);
}

/** /api/v1/company/projects/:project_id/workflows/:workflow_id/steps/:id(.:format) */
export function apiV1CompanyProjectWorkflowStepPath(project_id: ScalarType, workflow_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflows(.:format) */
export function apiV1CompanyProjectWorkflowsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/workflows/:id(.:format) */
export function apiV1CompanyProjectWorkflowPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/repositories/available(.:format) */
export function availableApiV1CompanyProjectRepositoriesPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "repositories" + "/" + "available" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/repositories/branches(.:format) */
export function branchesApiV1CompanyProjectRepositoriesPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "repositories" + "/" + "branches" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/repositories(.:format) */
export function apiV1CompanyProjectRepositoriesPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "repositories" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/repositories/:id(.:format) */
export function apiV1CompanyProjectRepositoryPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "repositories" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/assets/:id/download(.:format) */
export function downloadApiV1CompanyProjectAssetPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "assets" + "/" + id + "/" + "download" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/assets/:id/versions(.:format) */
export function versionsApiV1CompanyProjectAssetPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "assets" + "/" + id + "/" + "versions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/assets/:id/restore(.:format) */
export function restoreApiV1CompanyProjectAssetPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "assets" + "/" + id + "/" + "restore" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/assets(.:format) */
export function apiV1CompanyProjectAssetsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/assets/:id(.:format) */
export function apiV1CompanyProjectAssetPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "assets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/board/presets(.:format) */
export function presetsApiV1CompanyProjectBoardPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "presets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/board/columns/reorder(.:format) */
export function reorderApiV1CompanyProjectBoardColumnsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "columns" + "/" + "reorder" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/board/columns/:column_id/workflow_binding(.:format) */
export function apiV1CompanyProjectBoardColumnWorkflowBindingPath(project_id: ScalarType, column_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "columns" + "/" + column_id + "/" + "workflow_binding" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","column_id","format"]);
}

/** /api/v1/company/projects/:project_id/board/columns(.:format) */
export function apiV1CompanyProjectBoardColumnsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "columns" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/board/columns/new(.:format) */
export function newApiV1CompanyProjectBoardColumnPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "columns" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/board/columns/:id/edit(.:format) */
export function editApiV1CompanyProjectBoardColumnPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "columns" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/board/columns/:id(.:format) */
export function apiV1CompanyProjectBoardColumnPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "columns" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/board/activities(.:format) */
export function apiV1CompanyProjectBoardActivitiesPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "activities" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/board/view_presets(.:format) */
export function apiV1CompanyProjectBoardViewPresetsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "view_presets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/board/view_presets/:id(.:format) */
export function apiV1CompanyProjectBoardViewPresetPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "view_presets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/board/tasks/:id/move(.:format) */
export function moveApiV1CompanyProjectBoardTaskPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "tasks" + "/" + id + "/" + "move" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/board/tasks/:id/trigger_workflow(.:format) */
export function triggerWorkflowApiV1CompanyProjectBoardTaskPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "tasks" + "/" + id + "/" + "trigger_workflow" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/board/tasks/:id/workflow_runs(.:format) */
export function workflowRunsApiV1CompanyProjectBoardTaskPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "tasks" + "/" + id + "/" + "workflow_runs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/board/tasks/:task_id/comments(.:format) */
export function apiV1CompanyProjectBoardTaskCommentsPath(project_id: ScalarType, task_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "tasks" + "/" + task_id + "/" + "comments" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","task_id","format"]);
}

/** /api/v1/company/projects/:project_id/board/tasks/:task_id/assets(.:format) */
export function apiV1CompanyProjectBoardTaskAssetsPath(project_id: ScalarType, task_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "tasks" + "/" + task_id + "/" + "assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","task_id","format"]);
}

/** /api/v1/company/projects/:project_id/board/tasks/:task_id/assets/:id(.:format) */
export function apiV1CompanyProjectBoardTaskAssetPath(project_id: ScalarType, task_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "tasks" + "/" + task_id + "/" + "assets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","task_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/board/tasks/:task_id/waits/:id(.:format) */
export function apiV1CompanyProjectBoardTaskWaitPath(project_id: ScalarType, task_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "tasks" + "/" + task_id + "/" + "waits" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","task_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/board/tasks/:task_id/transitions(.:format) */
export function apiV1CompanyProjectBoardTaskTransitionsPath(project_id: ScalarType, task_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "tasks" + "/" + task_id + "/" + "transitions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","task_id","format"]);
}

/** /api/v1/company/projects/:project_id/board/tasks/:task_id/activities(.:format) */
export function apiV1CompanyProjectBoardTaskActivitiesPath(project_id: ScalarType, task_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "tasks" + "/" + task_id + "/" + "activities" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","task_id","format"]);
}

/** /api/v1/company/projects/:project_id/board/tasks/:task_id/statistics(.:format) */
export function apiV1CompanyProjectBoardTaskStatisticsPath(project_id: ScalarType, task_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "tasks" + "/" + task_id + "/" + "statistics" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","task_id","format"]);
}

/** /api/v1/company/projects/:project_id/board/tasks(.:format) */
export function apiV1CompanyProjectBoardTasksPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "tasks" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/board/tasks/new(.:format) */
export function newApiV1CompanyProjectBoardTaskPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "tasks" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/board/tasks/:id/edit(.:format) */
export function editApiV1CompanyProjectBoardTaskPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "tasks" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/board/tasks/:id(.:format) */
export function apiV1CompanyProjectBoardTaskPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + "/" + "tasks" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/board(.:format) */
export function apiV1CompanyProjectBoardPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "board" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/statistic/analytics/agent_activity(.:format) */
export function agentActivityApiV1CompanyProjectStatisticAnalyticsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "statistic" + "/" + "analytics" + "/" + "agent_activity" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/statistic/analytics/session_source_breakdown(.:format) */
export function sessionSourceBreakdownApiV1CompanyProjectStatisticAnalyticsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "statistic" + "/" + "analytics" + "/" + "session_source_breakdown" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/statistic/analytics/session_duration_distribution(.:format) */
export function sessionDurationDistributionApiV1CompanyProjectStatisticAnalyticsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "statistic" + "/" + "analytics" + "/" + "session_duration_distribution" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/statistic/analytics/cost_token_usage(.:format) */
export function costTokenUsageApiV1CompanyProjectStatisticAnalyticsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "statistic" + "/" + "analytics" + "/" + "cost_token_usage" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/statistic/analytics/filter_options(.:format) */
export function filterOptionsApiV1CompanyProjectStatisticAnalyticsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "statistic" + "/" + "analytics" + "/" + "filter_options" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/statistic/analytics(.:format) */
export function apiV1CompanyProjectStatisticAnalyticsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "statistic" + "/" + "analytics" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/statistic/workflow_costs(.:format) */
export function apiV1CompanyProjectStatisticWorkflowCostsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "statistic" + "/" + "workflow_costs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/statistic/overview(.:format) */
export function apiV1CompanyProjectStatisticOverviewPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "statistic" + "/" + "overview" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/statistic/recent_activity(.:format) */
export function apiV1CompanyProjectStatisticRecentActivityPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "statistic" + "/" + "recent_activity" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/statistic/workflow_runs(.:format) */
export function apiV1CompanyProjectStatisticWorkflowRunsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "statistic" + "/" + "workflow_runs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/statistic/board_task_distribution(.:format) */
export function apiV1CompanyProjectStatisticBoardTaskDistributionPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "statistic" + "/" + "board_task_distribution" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/terminal_sessions(.:format) */
export function apiV1CompanyProjectTerminalSessionsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "terminal_sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/terminal_sessions/:id(.:format) */
export function apiV1CompanyProjectTerminalSessionPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "terminal_sessions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:id/approve_step(.:format) */
export function approveStepApiV1CompanyProjectWorkflowRunPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + id + "/" + "approve_step" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:id/retry_step(.:format) */
export function retryStepApiV1CompanyProjectWorkflowRunPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + id + "/" + "retry_step" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:id/skip_step(.:format) */
export function skipStepApiV1CompanyProjectWorkflowRunPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + id + "/" + "skip_step" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:id/cancel(.:format) */
export function cancelApiV1CompanyProjectWorkflowRunPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + id + "/" + "cancel" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:workflow_run_id/assets/:id/export(.:format) */
export function exportApiV1CompanyProjectWorkflowRunWorkflowRunAssetPath(project_id: ScalarType, workflow_run_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + workflow_run_id + "/" + "assets" + "/" + id + "/" + "export" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_run_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:workflow_run_id/assets/:id/download(.:format) */
export function downloadApiV1CompanyProjectWorkflowRunWorkflowRunAssetPath(project_id: ScalarType, workflow_run_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + workflow_run_id + "/" + "assets" + "/" + id + "/" + "download" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_run_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:workflow_run_id/assets/export_all(.:format) */
export function exportAllApiV1CompanyProjectWorkflowRunWorkflowRunAssetsPath(project_id: ScalarType, workflow_run_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + workflow_run_id + "/" + "assets" + "/" + "export_all" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_run_id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:workflow_run_id/assets(.:format) */
export function apiV1CompanyProjectWorkflowRunWorkflowRunAssetsPath(project_id: ScalarType, workflow_run_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + workflow_run_id + "/" + "assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_run_id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs(.:format) */
export function apiV1CompanyProjectWorkflowRunsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:id(.:format) */
export function apiV1CompanyProjectWorkflowRunPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects(.:format) */
export function apiV1CompanyProjectsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/projects/:id(.:format) */
export function apiV1CompanyProjectPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin(.:format) */
export function adminRootPath(options?: object): string {
  return "/" + "admin" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/users/:id/impersonate(.:format) */
export function impersonateAdminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + "/" + "impersonate" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/users/:id/stop_impersonate(.:format) */
export function stopImpersonateAdminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + "/" + "stop_impersonate" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/users(.:format) */
export function adminUsersPath(options?: object): string {
  return "/" + "admin" + "/" + "users" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/users/new(.:format) */
export function newAdminUserPath(options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/users/:id/edit(.:format) */
export function editAdminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/users/:id(.:format) */
export function adminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/companies(.:format) */
export function adminCompaniesPath(options?: object): string {
  return "/" + "admin" + "/" + "companies" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/companies/new(.:format) */
export function newAdminCompanyPath(options?: object): string {
  return "/" + "admin" + "/" + "companies" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/companies/:id/edit(.:format) */
export function editAdminCompanyPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "companies" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/companies/:id(.:format) */
export function adminCompanyPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "companies" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/projects(.:format) */
export function adminProjectsPath(options?: object): string {
  return "/" + "admin" + "/" + "projects" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/projects/new(.:format) */
export function newAdminProjectPath(options?: object): string {
  return "/" + "admin" + "/" + "projects" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/projects/:id/edit(.:format) */
export function editAdminProjectPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "projects" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/projects/:id(.:format) */
export function adminProjectPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "projects" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/project_collaborators(.:format) */
export function adminProjectCollaboratorsPath(options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/project_collaborators/new(.:format) */
export function newAdminProjectCollaboratorPath(options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/project_collaborators/:id/edit(.:format) */
export function editAdminProjectCollaboratorPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/project_collaborators/:id(.:format) */
export function adminProjectCollaboratorPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/agent_credentials(.:format) */
export function adminAgentCredentialsPath(options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/agent_credentials/new(.:format) */
export function newAdminAgentCredentialPath(options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/agent_credentials/:id/edit(.:format) */
export function editAdminAgentCredentialPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/agent_credentials/:id(.:format) */
export function adminAgentCredentialPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/terminal_sessions(.:format) */
export function adminTerminalSessionsPath(options?: object): string {
  return "/" + "admin" + "/" + "terminal_sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/terminal_sessions/:id(.:format) */
export function adminTerminalSessionPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "terminal_sessions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/session_logs(.:format) */
export function adminSessionLogsPath(options?: object): string {
  return "/" + "admin" + "/" + "session_logs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/session_logs/:id(.:format) */
export function adminSessionLogPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "session_logs" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/assets(.:format) */
export function adminAssetsPath(options?: object): string {
  return "/" + "admin" + "/" + "assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/assets/:id(.:format) */
export function adminAssetPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "assets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/asset_versions(.:format) */
export function adminAssetVersionsPath(options?: object): string {
  return "/" + "admin" + "/" + "asset_versions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/asset_versions/:id(.:format) */
export function adminAssetVersionPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "asset_versions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/tool_results(.:format) */
export function adminToolResultsPath(options?: object): string {
  return "/" + "admin" + "/" + "tool_results" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/tool_results/:id(.:format) */
export function adminToolResultPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "tool_results" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/contact_requests(.:format) */
export function adminContactRequestsPath(options?: object): string {
  return "/" + "admin" + "/" + "contact_requests" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/contact_requests/:id(.:format) */
export function adminContactRequestPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "contact_requests" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/agents(.:format) */
export function adminAgentsPath(options?: object): string {
  return "/" + "admin" + "/" + "agents" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/agents/:id(.:format) */
export function adminAgentPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "agents" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/boards(.:format) */
export function adminBoardsPath(options?: object): string {
  return "/" + "admin" + "/" + "boards" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/boards/:id(.:format) */
export function adminBoardPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "boards" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/board_activities(.:format) */
export function adminBoardActivitiesPath(options?: object): string {
  return "/" + "admin" + "/" + "board_activities" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/board_activities/:id(.:format) */
export function adminBoardActivityPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "board_activities" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/board_columns(.:format) */
export function adminBoardColumnsPath(options?: object): string {
  return "/" + "admin" + "/" + "board_columns" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/board_columns/:id(.:format) */
export function adminBoardColumnPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "board_columns" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/board_tasks(.:format) */
export function adminBoardTasksPath(options?: object): string {
  return "/" + "admin" + "/" + "board_tasks" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/board_tasks/:id(.:format) */
export function adminBoardTaskPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "board_tasks" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/board_view_presets(.:format) */
export function adminBoardViewPresetsPath(options?: object): string {
  return "/" + "admin" + "/" + "board_view_presets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/board_view_presets/:id(.:format) */
export function adminBoardViewPresetPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "board_view_presets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/column_transitions(.:format) */
export function adminColumnTransitionsPath(options?: object): string {
  return "/" + "admin" + "/" + "column_transitions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/column_transitions/:id(.:format) */
export function adminColumnTransitionPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "column_transitions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/column_workflow_bindings(.:format) */
export function adminColumnWorkflowBindingsPath(options?: object): string {
  return "/" + "admin" + "/" + "column_workflow_bindings" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/column_workflow_bindings/:id(.:format) */
export function adminColumnWorkflowBindingPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "column_workflow_bindings" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/config_items(.:format) */
export function adminConfigItemsPath(options?: object): string {
  return "/" + "admin" + "/" + "config_items" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/config_items/:id(.:format) */
export function adminConfigItemPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "config_items" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/integrations(.:format) */
export function adminIntegrationsPath(options?: object): string {
  return "/" + "admin" + "/" + "integrations" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/integrations/:id(.:format) */
export function adminIntegrationPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "integrations" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/mcp_servers(.:format) */
export function adminMCPServersPath(options?: object): string {
  return "/" + "admin" + "/" + "mcp_servers" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/mcp_servers/:id(.:format) */
export function adminMCPServerPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "mcp_servers" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/repositories(.:format) */
export function adminRepositoriesPath(options?: object): string {
  return "/" + "admin" + "/" + "repositories" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/repositories/:id(.:format) */
export function adminRepositoryPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "repositories" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/skills(.:format) */
export function adminSkillsPath(options?: object): string {
  return "/" + "admin" + "/" + "skills" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/skills/:id(.:format) */
export function adminSkillPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "skills" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/tools(.:format) */
export function adminToolsPath(options?: object): string {
  return "/" + "admin" + "/" + "tools" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/tools/:id(.:format) */
export function adminToolPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "tools" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/tool_files(.:format) */
export function adminToolFilesPath(options?: object): string {
  return "/" + "admin" + "/" + "tool_files" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/tool_files/:id(.:format) */
export function adminToolFilePath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "tool_files" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/workflows(.:format) */
export function adminWorkflowsPath(options?: object): string {
  return "/" + "admin" + "/" + "workflows" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/workflows/:id(.:format) */
export function adminWorkflowPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "workflows" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/workflow_runs(.:format) */
export function adminWorkflowRunsPath(options?: object): string {
  return "/" + "admin" + "/" + "workflow_runs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/workflow_runs/:id(.:format) */
export function adminWorkflowRunPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "workflow_runs" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/workflow_run_assets(.:format) */
export function adminWorkflowRunAssetsPath(options?: object): string {
  return "/" + "admin" + "/" + "workflow_run_assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/workflow_run_assets/:id(.:format) */
export function adminWorkflowRunAssetPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "workflow_run_assets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/steps(.:format) */
export function adminStepsPath(options?: object): string {
  return "/" + "admin" + "/" + "steps" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/steps/:id(.:format) */
export function adminStepPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "steps" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/step_runs(.:format) */
export function adminStepRunsPath(options?: object): string {
  return "/" + "admin" + "/" + "step_runs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/step_runs/:id(.:format) */
export function adminStepRunPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "step_runs" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/sub_steps(.:format) */
export function adminSubStepsPath(options?: object): string {
  return "/" + "admin" + "/" + "sub_steps" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/sub_steps/:id(.:format) */
export function adminSubStepPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "sub_steps" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/sub_step_runs(.:format) */
export function adminSubStepRunsPath(options?: object): string {
  return "/" + "admin" + "/" + "sub_step_runs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/sub_step_runs/:id(.:format) */
export function adminSubStepRunPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "sub_step_runs" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/task_comments(.:format) */
export function adminTaskCommentsPath(options?: object): string {
  return "/" + "admin" + "/" + "task_comments" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/task_comments/:id(.:format) */
export function adminTaskCommentPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "task_comments" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/task_assets(.:format) */
export function adminTaskAssetsPath(options?: object): string {
  return "/" + "admin" + "/" + "task_assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/task_assets/:id(.:format) */
export function adminTaskAssetPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "task_assets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/usage_statistics(.:format) */
export function adminUsageStatisticsPath(options?: object): string {
  return "/" + "admin" + "/" + "usage_statistics" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/usage_statistics/:id(.:format) */
export function adminUsageStatisticPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "usage_statistics" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/namespace_resource_quotas(.:format) */
export function adminNamespaceResourceQuotasPath(options?: object): string {
  return "/" + "admin" + "/" + "namespace_resource_quotas" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/namespace_resource_quotas/new(.:format) */
export function newAdminNamespaceResourceQuotaPath(options?: object): string {
  return "/" + "admin" + "/" + "namespace_resource_quotas" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/namespace_resource_quotas/:id/edit(.:format) */
export function editAdminNamespaceResourceQuotaPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "namespace_resource_quotas" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/namespace_resource_quotas/:id(.:format) */
export function adminNamespaceResourceQuotaPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "namespace_resource_quotas" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** / */
export function rootPath(options?: object): string {
  return "/" + $buildOptions(options, []);
}

/** /docs */
export function oasRailsPath(options?: object): string {
  return "/" + "docs" + $buildOptions(options, []);
}

/** /letter_opener */
export function letterOpenerWebPath(options?: object): string {
  return "/" + "letter_opener" + $buildOptions(options, []);
}

/** /letter_opener/ */
export function letterOpenerWebLettersPath(options?: object): string {
  return "/" + "letter_opener" + "/" + $buildOptions(options, []);
}

/** /letter_opener/clear(.:format) */
export function letterOpenerWebClearLettersPath(options?: object): string {
  return "/" + "letter_opener" + "/" + "clear" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /letter_opener/:id(/:style)(.:format) */
export function letterOpenerWebLetterPath(id: ScalarType, options?: object): string {
  return "/" + "letter_opener" + "/" + id + ($hasPresentOwnProperty(options, "style") ? "/" + (options as any).style : "") + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","style","format"]);
}

/** /letter_opener/:id/delete(.:format) */
export function letterOpenerWebDeleteLetterPath(id: ScalarType, options?: object): string {
  return "/" + "letter_opener" + "/" + id + "/" + "delete" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /privacy-policy(.:format) */
export function privacyPolicyPath(options?: object): string {
  return "/" + "privacy-policy" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /terms-of-service(.:format) */
export function termsOfServicePath(options?: object): string {
  return "/" + "terms-of-service" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}
