/* tslint:disable */
/* This is generated by ts_routes-rails */

export type ScalarType = string | number | boolean;

function $buildOptions(options: any, names: string[]): string {
  if (options) {
    let anchor = "";
    const q = [] as string[];
    for (const key of Object.keys(options)) {
      if (names.indexOf(key) !== -1) {
        // the key is already consumed
        continue;
      }

      const value = options[key];

      if (key === "anchor") {
        anchor = `#${$encode(value)}`;
      } else {
        $buildQuery(q, key, value);
      }
    }
    return (q.length > 0 ? "?" + q.join("&") : "") + anchor;
  } else {
    return "";
  }
}

function $buildQuery(q: string[], key: string, value: any) {
  if ($isScalarType(value)) {
    q.push(`${$encode(key)}=${$encode(value)}`);
  } else if (Array.isArray(value)) {
    for (const v of value) {
      $buildQuery(q, `${key}[]`, v);
    }
  } else if (value != null) {
    // i.e. non-null, non-scalar, non-array type
    for (const k of Object.keys(value)) {
      $buildQuery(q, `${key}[${k}]`, value[k]);
    }
  }
}

function $encode(value: any): string {
  return encodeURIComponent(value);
}

function $isScalarType(value: any): value is ScalarType {
  return (
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  );
}

function $isPresent(value: any): boolean {
  return value != null && ("" + value).length > 0;
}

function $hasPresentOwnProperty(options: any, key: string): boolean {
  return options && options.hasOwnProperty(key) && $isPresent(options[key]);
}

/** /action_mcp */
export function actionMCPPath(options?: object): string {
  return "/" + "action_mcp" + $buildOptions(options, []);
}

/** /action_mcp/up(.:format) */
export function actionMCPActionMCPHealthCheckPath(options?: object): string {
  return "/" + "action_mcp" + "/" + "up" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /action_mcp/ */
export function actionMCPMCPGetPath(options?: object): string {
  return "/" + "action_mcp" + "/" + $buildOptions(options, []);
}

/** /action_mcp/ */
export function actionMCPMCPPostPath(options?: object): string {
  return "/" + "action_mcp" + "/" + $buildOptions(options, []);
}

/** /action_mcp/ */
export function actionMCPMCPDeletePath(options?: object): string {
  return "/" + "action_mcp" + "/" + $buildOptions(options, []);
}

/** /api/v1/auth/:provider(.:format) */
export function apiV1AuthPath(provider: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "auth" + "/" + provider + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["provider","format"]);
}

/** /api/v1/auth/:provider/callback(.:format) */
export function apiV1AuthCallbackPath(provider: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "auth" + "/" + provider + "/" + "callback" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["provider","format"]);
}

/** /api/v1/auth/failure(.:format) */
export function apiV1AuthFailurePath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "auth" + "/" + "failure" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/sessions(.:format) */
export function apiV1SessionsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/current_user(.:format) */
export function apiV1CurrentUserPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "current_user" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/assets/presign(.:format) */
export function presignApiV1AssetsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "assets" + "/" + "presign" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/assets/upload(.:format) */
export function uploadApiV1AssetsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "assets" + "/" + "upload" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/terminal_sessions/:id/finish(.:format) */
export function finishApiV1TerminalSessionPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "terminal_sessions" + "/" + id + "/" + "finish" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/terminal_sessions(.:format) */
export function apiV1TerminalSessionsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "terminal_sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/terminal_sessions/:id(.:format) */
export function apiV1TerminalSessionPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "terminal_sessions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/internal/ws_auth(.:format) */
export function apiV1InternalWsAuthPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "internal" + "/" + "ws_auth" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/internal/usage_statistics(.:format) */
export function apiV1InternalUsageStatisticsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "internal" + "/" + "usage_statistics" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/statistic/overview(.:format) */
export function apiV1CompanyStatisticOverviewPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "statistic" + "/" + "overview" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/statistic/workflow_runs(.:format) */
export function apiV1CompanyStatisticWorkflowRunsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "statistic" + "/" + "workflow_runs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/statistic/board_task_distribution(.:format) */
export function apiV1CompanyStatisticBoardTaskDistributionPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "statistic" + "/" + "board_task_distribution" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/integrations/github_setup(.:format) */
export function githubSetupApiV1CompanyIntegrationsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "integrations" + "/" + "github_setup" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/integrations(.:format) */
export function apiV1CompanyIntegrationsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "integrations" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/integrations/:id(.:format) */
export function apiV1CompanyIntegrationPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "integrations" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/users(.:format) */
export function apiV1CompanyUsersPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "users" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/users/:id(.:format) */
export function apiV1CompanyUserPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "users" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/config_items(.:format) */
export function apiV1CompanyConfigItemsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "config_items" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/config_items/:id(.:format) */
export function apiV1CompanyConfigItemPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "config_items" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/agents(.:format) */
export function apiV1CompanyAgentsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "agents" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/agents/:id(.:format) */
export function apiV1CompanyAgentPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "agents" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/tools(.:format) */
export function apiV1CompanyToolsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "tools" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/tools/:id(.:format) */
export function apiV1CompanyToolPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "tools" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/mcp_servers(.:format) */
export function apiV1CompanyMCPServersPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "mcp_servers" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/mcp_servers/:id(.:format) */
export function apiV1CompanyMCPServerPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "mcp_servers" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/skills(.:format) */
export function apiV1CompanySkillsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "skills" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/skills/:id(.:format) */
export function apiV1CompanySkillPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "skills" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/workflows/:workflow_id/steps/reorder(.:format) */
export function reorderApiV1CompanyWorkflowStepsPath(workflow_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + "/" + "reorder" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["workflow_id","format"]);
}

/** /api/v1/company/workflows/:workflow_id/steps(.:format) */
export function apiV1CompanyWorkflowStepsPath(workflow_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["workflow_id","format"]);
}

/** /api/v1/company/workflows/:workflow_id/steps/:id(.:format) */
export function apiV1CompanyWorkflowStepPath(workflow_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["workflow_id","id","format"]);
}

/** /api/v1/company/workflows(.:format) */
export function apiV1CompanyWorkflowsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "workflows" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/workflows/:id(.:format) */
export function apiV1CompanyWorkflowPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "workflows" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/repositories/available(.:format) */
export function availableApiV1CompanyRepositoriesPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "repositories" + "/" + "available" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/repositories/branches(.:format) */
export function branchesApiV1CompanyRepositoriesPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "repositories" + "/" + "branches" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/repositories(.:format) */
export function apiV1CompanyRepositoriesPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "repositories" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/repositories/:id(.:format) */
export function apiV1CompanyRepositoryPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "repositories" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/assets/:id/download(.:format) */
export function downloadApiV1CompanyAssetPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "assets" + "/" + id + "/" + "download" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/assets/:id/versions(.:format) */
export function versionsApiV1CompanyAssetPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "assets" + "/" + id + "/" + "versions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/assets/:id/restore(.:format) */
export function restoreApiV1CompanyAssetPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "assets" + "/" + id + "/" + "restore" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/assets(.:format) */
export function apiV1CompanyAssetsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/assets/:id(.:format) */
export function apiV1CompanyAssetPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "assets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/terminal_sessions/:terminal_session_id/artifacts/review(.:format) */
export function reviewApiV1CompanyTerminalSessionArtifactsPath(terminal_session_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "terminal_sessions" + "/" + terminal_session_id + "/" + "artifacts" + "/" + "review" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["terminal_session_id","format"]);
}

/** /api/v1/company/terminal_sessions/:terminal_session_id/artifacts/:id/download(.:format) */
export function downloadApiV1CompanyTerminalSessionArtifactPath(terminal_session_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "terminal_sessions" + "/" + terminal_session_id + "/" + "artifacts" + "/" + id + "/" + "download" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["terminal_session_id","id","format"]);
}

/** /api/v1/company/terminal_sessions/:terminal_session_id/artifacts(.:format) */
export function apiV1CompanyTerminalSessionArtifactsPath(terminal_session_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "terminal_sessions" + "/" + terminal_session_id + "/" + "artifacts" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["terminal_session_id","format"]);
}

/** /api/v1/company/terminal_sessions(.:format) */
export function apiV1CompanyTerminalSessionsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "terminal_sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/terminal_sessions/:id(.:format) */
export function apiV1CompanyTerminalSessionPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "terminal_sessions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/company/projects/:project_id/collaborators(.:format) */
export function apiV1CompanyProjectCollaboratorsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "collaborators" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/collaborators/:id(.:format) */
export function apiV1CompanyProjectCollaboratorPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "collaborators" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/config_items(.:format) */
export function apiV1CompanyProjectConfigItemsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "config_items" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/config_items/:id(.:format) */
export function apiV1CompanyProjectConfigItemPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "config_items" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/agents(.:format) */
export function apiV1CompanyProjectAgentsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "agents" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/agents/:id(.:format) */
export function apiV1CompanyProjectAgentPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "agents" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/tools(.:format) */
export function apiV1CompanyProjectToolsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "tools" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/tools/:id(.:format) */
export function apiV1CompanyProjectToolPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "tools" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/mcp_servers(.:format) */
export function apiV1CompanyProjectMCPServersPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "mcp_servers" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/mcp_servers/:id(.:format) */
export function apiV1CompanyProjectMCPServerPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "mcp_servers" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/skills(.:format) */
export function apiV1CompanyProjectSkillsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "skills" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/skills/:id(.:format) */
export function apiV1CompanyProjectSkillPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "skills" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflows/:workflow_id/steps/reorder(.:format) */
export function reorderApiV1CompanyProjectWorkflowStepsPath(project_id: ScalarType, workflow_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + "/" + "reorder" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_id","format"]);
}

/** /api/v1/company/projects/:project_id/workflows/:workflow_id/steps(.:format) */
export function apiV1CompanyProjectWorkflowStepsPath(project_id: ScalarType, workflow_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_id","format"]);
}

/** /api/v1/company/projects/:project_id/workflows/:workflow_id/steps/:id(.:format) */
export function apiV1CompanyProjectWorkflowStepPath(project_id: ScalarType, workflow_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + workflow_id + "/" + "steps" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflows(.:format) */
export function apiV1CompanyProjectWorkflowsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/workflows/:id(.:format) */
export function apiV1CompanyProjectWorkflowPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/repositories/available(.:format) */
export function availableApiV1CompanyProjectRepositoriesPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "repositories" + "/" + "available" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/repositories/branches(.:format) */
export function branchesApiV1CompanyProjectRepositoriesPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "repositories" + "/" + "branches" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/repositories(.:format) */
export function apiV1CompanyProjectRepositoriesPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "repositories" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/repositories/:id(.:format) */
export function apiV1CompanyProjectRepositoryPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "repositories" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/assets/:id/download(.:format) */
export function downloadApiV1CompanyProjectAssetPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "assets" + "/" + id + "/" + "download" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/assets/:id/versions(.:format) */
export function versionsApiV1CompanyProjectAssetPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "assets" + "/" + id + "/" + "versions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/assets/:id/restore(.:format) */
export function restoreApiV1CompanyProjectAssetPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "assets" + "/" + id + "/" + "restore" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/assets(.:format) */
export function apiV1CompanyProjectAssetsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/assets/:id(.:format) */
export function apiV1CompanyProjectAssetPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "assets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/statistic/analytics(.:format) */
export function apiV1CompanyProjectStatisticAnalyticsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "statistic" + "/" + "analytics" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/statistic/analytics/agent_activity(.:format) */
export function agentActivityApiV1CompanyProjectStatisticAnalyticsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "statistic" + "/" + "analytics" + "/" + "agent_activity" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/terminal_sessions(.:format) */
export function apiV1CompanyProjectTerminalSessionsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "terminal_sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/terminal_sessions/:id(.:format) */
export function apiV1CompanyProjectTerminalSessionPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "terminal_sessions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs(.:format) */
export function apiV1CompanyProjectWorkflowRunsPath(project_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:id(.:format) */
export function apiV1CompanyProjectWorkflowRunPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:id/approve_step(.:format) */
export function approveStepApiV1CompanyProjectWorkflowRunPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + id + "/" + "approve_step" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:id/retry_step(.:format) */
export function retryStepApiV1CompanyProjectWorkflowRunPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + id + "/" + "retry_step" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:id/skip_step(.:format) */
export function skipStepApiV1CompanyProjectWorkflowRunPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + id + "/" + "skip_step" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:id/cancel(.:format) */
export function cancelApiV1CompanyProjectWorkflowRunPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + id + "/" + "cancel" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflows/:id/duplicate(.:format) */
export function duplicateApiV1CompanyProjectWorkflowPath(project_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflows" + "/" + id + "/" + "duplicate" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:workflow_run_id/assets(.:format) */
export function apiV1CompanyProjectWorkflowRunAssetsPath(project_id: ScalarType, workflow_run_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + workflow_run_id + "/" + "assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_run_id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:workflow_run_id/assets/export_all(.:format) */
export function exportAllApiV1CompanyProjectWorkflowRunAssetsPath(project_id: ScalarType, workflow_run_id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + workflow_run_id + "/" + "assets" + "/" + "export_all" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_run_id","format"]);
}

/** /api/v1/company/projects/:project_id/workflow_runs/:workflow_run_id/assets/:id/export(.:format) */
export function exportApiV1CompanyProjectWorkflowRunAssetPath(project_id: ScalarType, workflow_run_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + project_id + "/" + "workflow_runs" + "/" + workflow_run_id + "/" + "assets" + "/" + id + "/" + "export" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["project_id","workflow_run_id","id","format"]);
}

/** /api/v1/company/projects(.:format) */
export function apiV1CompanyProjectsPath(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/company/projects/:id(.:format) */
export function apiV1CompanyProjectPath(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "company" + "/" + "projects" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin(.:format) */
export function adminRootPath(options?: object): string {
  return "/" + "admin" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/users/:id/impersonate(.:format) */
export function impersonateAdminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + "/" + "impersonate" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/users/:id/stop_impersonate(.:format) */
export function stopImpersonateAdminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + "/" + "stop_impersonate" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/users(.:format) */
export function adminUsersPath(options?: object): string {
  return "/" + "admin" + "/" + "users" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/users/new(.:format) */
export function newAdminUserPath(options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/users/:id/edit(.:format) */
export function editAdminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/users/:id(.:format) */
export function adminUserPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/companies(.:format) */
export function adminCompaniesPath(options?: object): string {
  return "/" + "admin" + "/" + "companies" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/companies/new(.:format) */
export function newAdminCompanyPath(options?: object): string {
  return "/" + "admin" + "/" + "companies" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/companies/:id/edit(.:format) */
export function editAdminCompanyPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "companies" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/companies/:id(.:format) */
export function adminCompanyPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "companies" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/projects(.:format) */
export function adminProjectsPath(options?: object): string {
  return "/" + "admin" + "/" + "projects" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/projects/new(.:format) */
export function newAdminProjectPath(options?: object): string {
  return "/" + "admin" + "/" + "projects" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/projects/:id/edit(.:format) */
export function editAdminProjectPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "projects" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/projects/:id(.:format) */
export function adminProjectPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "projects" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/project_collaborators(.:format) */
export function adminProjectCollaboratorsPath(options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/project_collaborators/new(.:format) */
export function newAdminProjectCollaboratorPath(options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/project_collaborators/:id/edit(.:format) */
export function editAdminProjectCollaboratorPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/project_collaborators/:id(.:format) */
export function adminProjectCollaboratorPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "project_collaborators" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/agent_credentials(.:format) */
export function adminAgentCredentialsPath(options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/agent_credentials/new(.:format) */
export function newAdminAgentCredentialPath(options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/agent_credentials/:id/edit(.:format) */
export function editAdminAgentCredentialPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/agent_credentials/:id(.:format) */
export function adminAgentCredentialPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "agent_credentials" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/terminal_sessions(.:format) */
export function adminTerminalSessionsPath(options?: object): string {
  return "/" + "admin" + "/" + "terminal_sessions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/terminal_sessions/:id(.:format) */
export function adminTerminalSessionPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "terminal_sessions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/session_logs(.:format) */
export function adminSessionLogsPath(options?: object): string {
  return "/" + "admin" + "/" + "session_logs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/session_logs/:id(.:format) */
export function adminSessionLogPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "session_logs" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/assets(.:format) */
export function adminAssetsPath(options?: object): string {
  return "/" + "admin" + "/" + "assets" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/assets/:id(.:format) */
export function adminAssetPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "assets" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/asset_versions(.:format) */
export function adminAssetVersionsPath(options?: object): string {
  return "/" + "admin" + "/" + "asset_versions" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/asset_versions/:id(.:format) */
export function adminAssetVersionPath(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "asset_versions" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** / */
export function rootPath(options?: object): string {
  return "/" + $buildOptions(options, []);
}

/** /docs */
export function oasRailsPath(options?: object): string {
  return "/" + "docs" + $buildOptions(options, []);
}

/** /letter_opener */
export function letterOpenerWebPath(options?: object): string {
  return "/" + "letter_opener" + $buildOptions(options, []);
}

/** /letter_opener/ */
export function letterOpenerWebLettersPath(options?: object): string {
  return "/" + "letter_opener" + "/" + $buildOptions(options, []);
}

/** /letter_opener/clear(.:format) */
export function letterOpenerWebClearLettersPath(options?: object): string {
  return "/" + "letter_opener" + "/" + "clear" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /letter_opener/:id(/:style)(.:format) */
export function letterOpenerWebLetterPath(id: ScalarType, options?: object): string {
  return "/" + "letter_opener" + "/" + id + ($hasPresentOwnProperty(options, "style") ? "/" + (options as any).style : "") + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","style","format"]);
}

/** /letter_opener/:id/delete(.:format) */
export function letterOpenerWebDeleteLetterPath(id: ScalarType, options?: object): string {
  return "/" + "letter_opener" + "/" + id + "/" + "delete" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}
