apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: palad-staging
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "replace_me",
          "password": "replace_me",
          "email": "replace_me",
          "auth": "replace_me"
        }
      }
    }
