/**
 * Application Routes
 *
 * This file serves as a wrapper around both backend (Rails) and frontend routes.
 * It provides a consistent interface for accessing all routes in the application.
 */

import * as BackendRoutes from './api/routes';

// Backend routes are generated by ts_routes-rails
const backend = {
  ...BackendRoutes,
};

// Frontend routes are defined manually here to match the SPA routing
const frontend = {
  rootPath: '/',
} as const;

// Combine both types of routes into a single export
export const Routes = {
  backend,
  frontend,
};

export default Routes;
