/**
 * Application Routes
 *
 * This file serves as a wrapper around both backend (Rails) and frontend routes.
 * It provides a consistent interface for accessing all routes in the application.
 */

import * as BackendRoutes from './api/routes';

// Backend routes are generated by ts_routes-rails
const backend = {
  ...BackendRoutes,
};

// Frontend routes are defined manually here to match the SPA routing
const frontend = {
  // Static routes
  rootPath: '/',
  loginPath: '/login',
  onboardingPath: '/onboarding',
  setupPath: '/setup',
  workspacePath: '/workspace',
  homePath: '/home',
  profilePath: '/profile',

  // Company routes
  companyPath: '/company',
  companyProjectsPath: '/company/projects',
  companyProjectPath: (projectId: string) => `/company/projects/${projectId}`,
  companyProjectTabPath: (projectId: string, tab: string) => `/company/projects/${projectId}/${tab}`,
  companyMembersPath: '/company/members',
  companySettingsPath: '/company/settings',
  companyConfigItemsPath: '/company/config-items',
  companyAgentsPath: '/company/agents',
  companyToolsPath: '/company/tools',
  companyMcpServersPath: '/company/mcp-servers',
  companySkillsPath: '/company/skills',
  companyBrandingPath: '/company/branding',
  companySessionsPath: '/company/sessions',
  companySessionNewPath: '/company/sessions/new',
  companySessionPath: (sessionId: string) => `/company/sessions/${sessionId}`,
  companyProjectSessionNewPath: (projectId: string) => `/company/projects/${projectId}/sessions/new`,
  companyProjectSessionPath: (projectId: string, sessionId: string) => `/company/projects/${projectId}/sessions/${sessionId}`,

  // Workflow routes
  workflowRunPath: (projectId: string, runId: string) => `/company/projects/${projectId}/workflow-runs/${runId}`,
  workflowBuilderPath: (workflowId: string) => `/workflow-builder/${workflowId}`,

  // Terminal test routes
  terminalTestPath: '/terminal-test',
  terminalTestSessionPath: (routeToken: string) => `/terminal-test/${routeToken}`,
} as const;

// Combine both types of routes into a single export
export const Routes = {
  backend,
  frontend,
};

export default Routes;
