authorization:
  otp_enabled: true

temporal:
  enabled: true
  ui_url: <%= ENV['TEMPORAL_UI_URL'] || 'https://temporal.qa.palad.com' %>

redis:
  ui_url: <%= ENV['REDIS_UI_URL'] || 'https://redis.qa.palad.com' %>
