project_name: Palad

domain: <%= ENV['DOMAIN'] || "lvh.me:4000" %>
asset_host: <%= ENV['ASSET_HOST'] || "lvh.me:4000" %>
protocol: "https"

anthropic:
  api_key: <%= ENV['ANTHROPIC_API_KEY'] %>

rails:
  secret_key_base: <%= ENV['RAILS_SECRET_KEY_BASE'] || "secret" %>
  port: <%= ENV['RAILS_PORT'] || 4000 %>

app:
  version: <%= ENV['APP_VERSION'] || `git rev-parse HEAD`.strip %>
  last_commiter:
    name: <%= ENV['AUTHOR_NAME'] || `git log -1 --pretty=format:'%an'`.strip %>
    email: <%= ENV['AUTHOR_EMAIL'] || `git log -1 --pretty=format:'%ae'`.strip %>

rollbar: # move tokens to infra code
  access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  js_access_token: <%= ENV['ROLLBAR_JS_ACCESS_TOKEN'] %>
  deploy_endpoint: <%= ENV['ROLLBAR_DEPLOY_ENDPOINT'] %>

database:
  name: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] || "127.0.0.1" %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  username: <%= ENV['DB_USERNAME'] || "postgres" %>
  password: <%= ENV['DB_PASSWORD'] || "" %>

mailer:
  address: <%= ENV["MAILER_ADDRESS"] %>
  port: <%= ENV["MAILER_PORT"] %>
  domain: <%= ENV['DOMAIN'] || "lvh.me:4000" %>
  user_name: <%= ENV['MAILER_USERNAME'] %>
  password: <%= ENV['MAILER_PASSWORD'] %>
  authentication: <%= ENV["MAILER_AUTHENTICATION"] || 'plain' %>

redis:
  url: <%= ENV['REDIS_URL'] || 'redis://redis:6379/1'%>
  ui_url: <%= ENV['REDIS_UI_URL'] || 'http://localhost:8081' %>

docs:
  login: <%= ENV['DOCS_LOGIN'] || 'user' %>
  password: <%= ENV['DOCS_PASSWORD'] || 'password' %>

admin:
  password: <%= ENV['ADMIN_PASSWORD'] || "adminpass" %>
  email: <%= ENV['SUPER_ADMIN_EMAIL'] || "admin@palad.ai" %>

aws:
  access_key_id:     <%= ENV['AWS_ACCESS_KEY_ID']%>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY']%>
  bucket:            <%= ENV['AWS_S3_BUCKET'] || 'fake' %>
  region:            <%= ENV['AWS_DEFAULT_REGION'] || 'fake' %>

mcp:
  name: palad-mcp-server

temporal:
  enabled: <%= ENV['TEMPORAL_ENABLED'] %>
  host: <%= ENV['TEMPORAL_HOST'] || 'temporal' %>
  port: <%= ENV['TEMPORAL_PORT'] || 7233 %>
  namespace: <%= ENV['TEMPORAL_NAMESPACE'] || 'default' %>
  task_queue: <%= ENV['TEMPORAL_TASK_QUEUE'] || 'palad_ruby' %>
  ui_url: <%= ENV['TEMPORAL_UI_URL'] || 'http://localhost:8080' %>

