name: Code Check

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      runner:
        required: false
        type: string
        default: ""
      needs-db:
        required: false
        type: boolean
        default: false
      timeout:
        required: false
        type: number
        default: 10
      image-tag:
        required: false
        type: string
        default: ""

env:
  REGISTRY: ghcr.io
  COMPOSE_FILE: docker-compose.ci.yml
  IMAGE: ghcr.io/${{ github.repository }}-web

jobs:
  check:
    name: Run
    runs-on: ${{ inputs.runner != '' && inputs.runner || vars.CI_RUNNER || 'ubuntu-latest' }}
    timeout-minutes: ${{ inputs.timeout }}
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: |
          IMAGE_TAG="${{ inputs.image-tag }}"

          if [ -z "$IMAGE_TAG" ]; then
            IMAGE_TAG="$(echo "$GITHUB_SHA" | cut -c1-7)"
          fi

          docker pull "${IMAGE}:${IMAGE_TAG}"
          docker tag  "${IMAGE}:${IMAGE_TAG}" web

      - name: Start database
        if: ${{ inputs.needs-db }}
        run: docker compose -f "$COMPOSE_FILE" up -d db redis

      - name: Wait for database
        if: ${{ inputs.needs-db }}
        run: |
          until docker compose -f "$COMPOSE_FILE" exec -T db pg_isready -U postgres; do sleep 1; done

      - name: Prepare database
        if: ${{ inputs.needs-db }}
        run: docker compose -f "$COMPOSE_FILE" run --rm --no-deps web bundle exec rails db:create db:migrate

      - name: Run check
        run: docker compose -f "$COMPOSE_FILE" run --rm --no-deps web make ${{ inputs.command }}

      - name: Tear down
        if: ${{ always() && inputs.needs-db }}
        run: docker compose -f "$COMPOSE_FILE" down --volumes --remove-orphans
